### ISSUE TITLE
Add Contact/Account does not allow for adding an Account only

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#10]
All other client apps (LAN/Web) have always provided for adding just an Account w/no Contact. The Mobile web app does not.

x-posted to the community

**Comment by jhershauer** [comment]
Yes, the mobile app supports adding an Account only. Click on "Accounts", then hit the Plus button in the upper right.

Add Account/Contact is just a shortcut that was added to the home page to make it easy to add both an Account and a Contact in a single step.

**Comment by rjledger** [comment]
Thanks!
I was using the Quick Action.. and it only does both.... 
See, you guys built something too good and I "blanked out" on the Account add.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
