### ISSUE TITLE
Create Account in mobile sets GlobalSyncId to Empty guid instead of null

### ISSUE THREAD

**Issue by cerichson** [Saleslogix/argos-saleslogix#107]
If you create an account anywhere in the system, the default value for the GlobalSyncId is null. If you create an account using the mobile platform, it is set to an Empty Guid. This trips up the OnBeforeDelete event in the Web Client and causes the account to no longer be able to be deleted. The correct behavior should be that the GlobalSyncId on an Account created with mobile should be null.

**Comment by rjledger** [comment]
@cerichson - which version(s)?

**Comment by cerichson** [comment]
I'm currently using 2.1 but I suspect that this is in 2.0+

**Comment by jbest84** [comment]
What version of Saleslogix? This would be an SData issue (mobile does not send that property as part of the payload).

**Comment by cerichson** [comment]
Saleslogix v8.0.0.8479

**Comment by jperona** [comment]
This is an issue in the sdata API and has been resolved

**Comment by rjledger** [comment]
Will we see a hot fix released to SData on this?
