### ISSUE TITLE
Scheduling an Activity - forced to select Account before Contact

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#11]
Most of us schedule an Activity w/an individual and typically look up the contact first and let it fill in the account automatically. This saves extra keystrokes and time.

The mobile web app will not let you do this.

**Comment by rjledger** [comment]
Daily use of the MW client has shown the current method of forcing an Account Look-up before doing a contact look-up is not only not consistent w/the way BOTH the Web And LAN client works.. but is a significant PITA and time-waste(too many clicks).

All customers who have seen this do not like the way it is working and have asked us to "fix it"....  Will it get "fixed".. it's "backwards" right now.

**Comment by wskidmore** [comment]
You can checkout the saleslogix branch: "topic-fields-dependOn-account". It allows you to choose a contact first, and it auto-populates account on selection too.

**Comment by rjledger** [comment]
Thanks! I'll give it a shot.
Will this get merged into the "2.0" master?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
It will yes, it's just going through the dev - code review - fix - repeat process before merging in.

**Comment by rjledger** [comment]
GREAT! Thanks!

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
