### ISSUE TITLE
2.2 - Tested Account list by using "GroupedList" functionality - does not work.

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#110]
When setting up a GroupedList w/Account, Contact, etc.. there's no vertical Scroll bar so you cannot get past the "first page" of 20. 

Really an argos-SDK issue but seen at the argos-saleslogix level

This will break a lot of systems that are using Grouped List(s).

**Comment by jbest84** [comment]
Can you edit GroupedList in the SDK and on line 54 of the Simplate, change `class="list grouped-list` to `class="overthrow list grouped-list` Does the scroll bar appear for you if that change is made? Let me know. Thanks!

**Comment by rjledger** [comment]
It worked.. sort of.
If I happen to “collapse” a group in the list and then scroll down it repeats the “query”  somehow and I end up with the Accounts listed multiple times.

I’m grouping by Account Uppercase First letter.

.. close but not quite right.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
The refresh issue is in another branch waiting for QA validation (should be in 2.2 within a day or 2): https://github.com/SageSalesLogix/argos-sdk/pull/9

**Comment by jbest84** [comment]
Fixed via: https://github.com/SageSalesLogix/argos-sdk/commit/2bab8f47bdd0de7b1e71805a318fe561a2a6f797

**Comment by rjledger** [comment]
Added the change from this and looks like GroupedList is looking good!

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by rjledger** [comment]
Additional test results…
If I have several “groups listed and collapse them all and the last one shows “n” records remaining.. the scroll bar is gone and it just sits there. If I then expand the last one the “loading” indicator comes up.. and we get additional records.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
That is true. The new continuousScrolling property (https://github.com/SageSalesLogix/argos-sdk/blob/2.2/src/List.js#L661) will require you to scroll to the bottom to fire the next page event. Perhaps we could:

A: Bring back the load more button, even for continuous scrolling
B: Have the grouped list set continousScrolling to false to bring back the load more button

**Comment by rjledger** [comment]
Based on what you said (“..will require you to scroll to the bottom to fire the next page event …”). The issue I’m seeing is that by collapsing the grouped sections, we can easily end up with a “short page” that’s not at the end.. hence we are “stuck”.

As a “C” proposal:
           Is it possible to grab the collapse event and use t to cause the next page event to fire?

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
I thought up a better fix: Have the grouped list override the base moreTemplate. Here is the changeset that fixes it: https://github.com/SageSalesLogix/argos-sdk/commit/49ac884fb3b58dadd165352ddd35650ca92825ab

**Comment by rjledger** [comment]
Testing your better fix on my "22 on 754" setup - (my production db as well ;-) .... Like it! When we collapse and end up on a "partial page" one can now simply click on the "Retrieve More Records" button and it works just fine!

**Comment by jbest84** [comment]
Good to hear!

**Comment by rjledger** [comment]
You are welcome.
If you guys are ok on it.. I'd consider the issue resolved - unless a better idea comes along ;-)

**Comment by jbest84** [comment]
I am OK with closing this issue. Thanks for the feedback.

**Comment by rjledger** [comment]
Glad to have been of assistance.. and thanks for jumping on the problem.

Always open to take a “poke” at mobility in my test and live production system. It’s something we use every day.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)
