### ISSUE TITLE
2.2 - Scheduling an Activity - phone number missing

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#117]
When you schedule an activity in Windows/LAN or SLX Web Client, it copies over the Workphone of the contact into Activity (PhoneNumber). Mobile does not.

By having the phone number in the Activity (detail), one can quickly dial and complete the activity. Otherwise you have to go to teh Contact (record).. dial there and it will add a history record when you are done.. BUT you still have the original Activity (record) and if you go back and complete it you now have "duplicate" history records related to the "Activity".

Simply adding PhoneNumber to Activity makes it clean(er) and also makes it work like Web and Windows/LAN.

**Comment by rjledger** [comment]
Any chance of this getting into 2.3?

**Comment by jperona** [comment]
RJ,
Seems reasonable.  I'll check with the team and also validate why this doesn't happen in the Business Model for consistency

**Comment by rjledger** [comment]
Thanks John!
I first noticed this after a complaint from a customer - they just could not understand why one could not simply "dial" right from the Activity.. complete it (Activity) on finish. 

The way it works now (all versions up to the present state of 2.3) they end up with two history records - (one from the call they initiated after "jumping" from the activity to the contact to make the call - and the one from manually going back to the Activity and completing it! ;-)

**Comment by jbest84** [comment]
Fixed in commit: https://github.com/Saleslogix/argos-saleslogix/commit/b8d7fa3ac1bfec74591ef0af99fcc9d3f82115a3

**Comment by jbest84** [comment]
@rjledger If this fix works for you, can we go ahead and close this? Thanks.

**Comment by rjledger** [comment]
Testing.... looks good to me
