### ISSUE TITLE
Scheduling/editing an Activity - Setting the Alarm - too restrictive

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#12]
The (GUI) setting of an alarm/reminder interval has the same limitation as the duration of an activity. Many times people will set an alarm for several days in advance or maybe in x minutes (or hrs). 

We need a change in the GUI  to allow for setting of things like a 3 day or 13 minute.. or 7 hr.. type of reminder alarms.

**Comment by rjledger** [comment]
Had a customer comment to me the LAN/Web approach is far better/easier/more flexiable to use than the current GUI in the mobile.

**Comment by wskidmore** [comment]
See Issue #9. There is now a duration field which is similar to the Web. It's a mixed autocomplete and picklist field enabling any custom values to be typed in various formats or you can use the picklist for the defaults.

**Comment by rjledger** [comment]
Yep.. tested fine!

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
