### ISSUE TITLE
When choosing an "Owner" too many choices - All versions of Mobility have this issue

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#121]
Just checked 2.2 - has the same problem:

Use is given list of templates, retired users, departments, etc - should only see Active Users and Teams.
 Choosing the "wrong owner" causes major data and synch issues. I've almost destroyed a production system by accident because of this - a major bug.

**Comment by jbest84** [comment]
@rjledger I had QA file a defect in our system. This will get fixed for 2.3.

**Comment by jbest84** [comment]
Fixed in commit: https://github.com/Saleslogix/argos-saleslogix/commit/b84f26c107160b300e4d38741b8e2e17bc351c7a
