### ISSUE TITLE
2.2 - Signature editor isn't loading properly

### ISSUE THREAD

**Issue by beckiblackburn** [Saleslogix/argos-saleslogix#125]
Errors are causing the signature control's "edit" view (signature.js) to not full load, and thus you can't actually add/edit a signature. I’ve attached my Firebug console and Chrome console, so that you can see the errors. The first error in both is just navigating to the Signature.js (signature_edit) view, but the subsequent errors are when I move my cursor around over the line as though I’m drawing the signature. And as you can see, due to the errors, no drawing actually registers. 

This exact customization worked perfectly in 2.1. I am wondering if perhaps due to the changes in navigation, it's not finding the .toolbar property correctly. 

Thanks!!

![mobilesignatureediterrorsfirebug](https://f.cloud.github.com/assets/459620/814988/1edaa8ba-ef20-11e2-86ed-36835239b1c0.jpg)
![mobilesignatureediterrorschrome](https://f.cloud.github.com/assets/459620/814989/1ede7846-ef20-11e2-8799-bd9c77e24393.jpg)

**Comment by jbest84** [comment]
Hi Becki! Thanks for the feedback. Here is the SDK change that fixes it: https://github.com/Saleslogix/argos-sdk/commit/dd3e367a42e565e7b2b5d56b65fe38a57eb9bd7d#diff-1

It did not make the 2.2 release because these changes were on the topic-metrics-2 branch. This branch was merged into our development branch AFTER 2.2 was released.

**Comment by beckiblackburn** [comment]
Awesome thanks!!

**Comment by jbest84** [comment]
No problem. You can cherry pick that commit onto your 2.2 branch if you want (sdk). This way you don't have to take all of the latest development changes. I usually use SourceTree for cherry picking, but I think the command line would be something like:

```
cd argos-sdk
git checkout 2.2
git cherry-pick dd3e367
```

**Comment by beckiblackburn** [comment]
I don't actually have a 2.2 branch of my own. Can I just physically make this change to my argos-sdk files for my customer, directly in AA before deploying changes? I want to make sure we're upgrade safe and all of that. By the way, this did fix it in my dev environment. Much appreciated. Would it be best to always download from here, vs the 'released' version? I suppose there may be other handy fixes here.

**Comment by rjledger** [comment]
Becki – I’d go ahead and do it - I do these types of changes all the time and you should have zero issues. Also, exporting the source(s) and using Beyond Compare goes a long ways as well ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by beckiblackburn** [comment]
Yep - been there and done that. That's how I could tell that the code in signature.js hadn't changed between 2.1 and 2.2.  I agree it's one of my favorite tools.

**Comment by rjledger** [comment]
I'm doing 100% of mobility dev outside of AA using WebStorm. Get to run off the "source" and use the "gist" to build via command prompt (build-module saleslogix). Have modified it and made one that does "buildDeploy-module" saleslogix. No AA at all!

**Comment by jbest84** [comment]
See "Building a Release Version" here: https://github.com/Saleslogix/argos-saleslogix#building-a-release-version if you want to build without AA. The link to the gist that RJ mentions is included in the steps too.

**Comment by beckiblackburn** [comment]
I always develop outside of AA, but find it easiest to deliver to the customer inside of an AA project - either via project backup or a web bundle. Deployment is now very easy with the way that it all registers in AA as a customization package. :-)

**Comment by rjledger** [comment]
@beckiblackburn - same here.. and there are situations where you have to change "core code" itself. EX: added the "F3" functionality (complete unscheduled activity). You have to mod the Saleslogix code directly to get it to work. Cannot do it in a custom module.

**Comment by jperona** [comment]
@RJ what do we need here to support this customization?  Ideally we don't
want you changing core ;)

On Wednesday, July 17, 2013, RJ Ledger wrote:

> @beckiblackburn https://github.com/beckiblackburn - same here.. and
> there are situations where you have to change "core code" itself. EX: added
> the "F3" functionality (complete unscheduled activity). You have to mod the
> Saleslogix code directly to get it to work. Cannot do it in a custom module.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Saleslogix/argos-saleslogix/issues/125#issuecomment-21147755
> .

## 

Thanks,
John

**Comment by rjledger** [comment]
John,
I change core all the time. Faster, easier, etc..

The biggest hang-up that tends to cause me to have to mod the core deals with “context”.. ex: what is “this.whatever” at a particular point/place..

Another area deals w/quick and immediate actions – re-ordering them.. as well as re-ordering “related sections” in the entities…  The present “customization module” approach is great for simple things but is way too messy for some of these customizations.

Good subject in general to have a conf call on. I can think of a ton of things – especially w/the 2.3 stuff.. right drawer.. that will need to be able to be easily customized.

rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
There is no easy way to handle the quick actions if you want to re-order all of them. Even if we provided a order flag or something of that nature, you would still need to touch all of them you want to re-order. The new right drawer is customizable. I registered the customization set as "right_drawer". Could you give an example for your first point? Generally "this" is bound to the view.

**Comment by jperona** [comment]
Thanks RJ,  Obviously, you can change core, but our goal would be for you
to extend so we can "upgrade" you for free and not break the customizations.

Happy to get a call together when I'm back in the office from Boston.

Thanks,
John

**Comment by rjledger** [comment]
@jperona - did not know you were in the "neighborhood" this week ;-) Just turn slightly west of north and I'm about 90 minutes away in NH.

Looking forward to the call. I'll work on my short (and long) list of items/areas impacting customization. Maybe we can come up with some things that would be useful for bootcamp.

**Comment by rjledger** [comment]
@jbest84 - Yep.. I had walked thru several scenarios on how to handle re-ordering of "things".. and kept coming back to the same conclusion.. no true easy way to do it except to go right into the "core" and cut-n-paste.
Great news on right_drawer.. putting down some ideas on just what we might do there.

The "this" issue tends to pop up if one is trying to build a custom add-on module which adds "immediate actions" (list actions) and needs to normally use "this".. but at that point you are not in the "view's" context.
