### ISSUE TITLE
2.2 - Two signatures on same edit form only saves last one changed.

### ISSUE THREAD

**Issue by beckiblackburn** [Saleslogix/argos-saleslogix#127]
I have 2 signature fields on the same edit form, one for customer signature and one for employee signature. I can 'edit' both signatures, so that on the edit view I do see them both rendered properly, but when I save, the detail view only shows the last one I changed. I can then edit again, and i see only the 1 populated that showed on the detail. So I add the signature again to the second field, and again see both rendered, but when I save, I only see the second field populated in the detail view and the first one is now blank again. 

Both signature fields are mapped to different entity properties, so it's not a matter of me just accidentally mapping them to the same field. But is the problem because they both have the same 'view' property of 'signature_edit'?  Do I need to add some sort of delegate binding in order for 2 signature fields to work?

**Comment by jbest84** [comment]
Can you verify the payload is empty that gets sent up to the server for the field that is missing?

**Comment by beckiblackburn** [comment]
Yes, I just pulled up the edit view, and the 'get' shows that CustomerSignature has data and EmployeeSignature is null. Then I edited the EmployeeSignature so that it would have data, but then when I saved, the 'put' shows that though yes the EmployeeSignature is now populated, the CustomerSignature is now null.  

HOWEVER, if I do modify them both, during the same edit, then they both save. So it's only if I already have one populated from a previous edit, and am adding the second signature. 

And worse yet - Now it appears to be working.... Something strange must have been cached. Hold tight, as I'm going to clear all my caches and try this again. This may be a false alarm. :-/

**Comment by beckiblackburn** [comment]
Oh wow - now toggling between test records, if I edit one, and then save it, and then edit the other record by "erasing" one of the signatures, then when I save, I'm seeing the first record's signature.. I am completely hoping it's my goofy machine.  Again - I'm going to do some serious clearing of data and cache, and then go through a detailed set of steps, and if I can replicate these oddities again, I'll send you the steps and screenshots.

**Comment by jbest84** [comment]
OK - Thanks

**Comment by beckiblackburn** [comment]
I tried to attach my steps, but git won't allow a word doc. I'm going to email that to you directly, if that's ok.

**Comment by jbest84** [comment]
Sure

**Comment by jbest84** [comment]
@beckiblackburn I have a fix for you in the SDK here: https://github.com/Saleslogix/argos-sdk/commit/6eb1b5f212f8c719b25805d155bcb300094f87b4

Let me know if this resolves it for you. I was able to reproduce this using an out of the box entity (Account) by setting the BusinessDescription and Notes field to signature. It only happens on the first save. If you look at the PUT request, it was setting the field that wasn't edit to null.

**Comment by beckiblackburn** [comment]
PERFECT!!! Works now as expected. You're brilliant. And thank you so much for the quick turnaround. :-)

**Comment by jbest84** [comment]
You are welcome!
