### ISSUE TITLE
Line chart suggestion

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#134]
to Charts folder added:
   GenertcLine.js - copied GenericBar.js and made (I hope) appropriate changes

to MetricWidget.js added:
   'line': 'chart_generic_line'

to MetricConfigure.js added:
    {'$key': 'line', '$descriptor': 'line'}

When configuring a line chart.. just not working.

Missing something simple here - right?

**Comment by jbest84** [comment]
In the application module, you need to register the line chart view with the id of "chart_generic_line"

**Comment by rjledger** [comment]
UGGGGGHHHH!.. Yep.. I just saw that.. interesting how one can easily forget the basics...

**Comment by rjledger** [comment]
Now I need to work on how the values for "x" & "Y" get assigned  just defaulting to what is there is producing "messy" charts w/no real meaning- tips?

**Comment by rjledger** [comment]
.. additional thought....
Right now you have bar and pie charts available as OOTB - I'd suggest you also need "line". Was working with a customer this am and showing them what was on the horizon.. and they said ".. it's missing a line chart.." They consider bar, pie, and line to be the minimum requirements - I tend to agree.

Possible to be in 23?

**Comment by jbest84** [comment]
Line chart has been added in the latest develop branch, and will be available OOTB in 3.3.
