### ISSUE TITLE
23 - Charts Configure turns off any other Charts

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#135]
Configuring a chart (change an existing one) and saving turns off all charts for that entity

**Comment by jbest84** [comment]
The configure screen is going to go away eventually (we want an admin to choose which widget sets to deploy out for mobile). However you can work around this issue by going into MetricConfigure.js and changing line 241 to enabled: true or attempt to extract the value from App.preferences.metrics if you want.
