### ISSUE TITLE
Passing a URL "Shortcut" to mobility

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#137]
This came up a while back - the ability to "pass" a URL shortcut and go to a specific EntityId (ex: ContactId.. or AccountId).

This is something we can do w/the Windows Client (slx:CONTACT/<contactId>) ans well as the web app.

I tried creating a "desktop shortcut" and it brings up the Mobility app in the browser.. but you login and you just land in the "defaultlocation".

The reason for this is to be able to support 3rd part apps that might have "url links" in them that point to Saleslogix "records" - Ex: a web based map app that has uploaded Account links.

Ideas?.. possible? stupid? ;-)

**Comment by jbest84** [comment]
I started an experimental topic branch for this (based on the new dojo/router). You can check out the topic-routing branches in the SDK and argos-saleslogix to see how it would work. Basically you can have a view register a route (example: "/some_view/edit/1"). When you change the hash to that route, it will load that view. There needs to be a bit more work to complete the story though (loading context, etc). Another benefit of using the router is it abstracts ReUI a bit more which will make it easier to replace in the future as there is only one route that uses ReUI.

**Comment by rjledger** [comment]
Sounds like a plan!

**Comment by jbest84** [comment]
Added by: https://github.com/Saleslogix/argos-saleslogix/commit/fd38a14490f77d551f16e99c4dd8d9fa964aee93

You can add /redirectTo/{viewId} at the end of the hash to get a redirect after login
