### ISSUE TITLE
Completing an Activity - No Account Issue

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#14]
Scenario:
   Yesterday was the third Thursday and as usual, there was an (Outlook) email reminder from Sage about the monthly on-line salesmeeting. This was in the form of a "meeting request" and Intellisynch automatically converted it to a Meeting type activity in SalesLogix. Of course it (the) SalesLogix Activity appeared w/no Account and no Contact info.

When I went to complete the activity in the mobile web app it gave me a Validation error/alert because there was no Account.. However, If you complete it in the WIndows/LAN or the Web client there is no such validation and it will complete (W/out an Account and/or Contact).

x-posted to the community

**Comment by jbest84** [comment]
Verified in the latest mobile this is no longer the case. You can complete activities with no account/contact.
