### ISSUE TITLE
23 - removal of the word "Sage"... found a few left

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#147]
I have a tool called "SR32" and it's great for searching source files. Found "Sage Saleslogix" in the following:
  ../localization/de, fr, it, ru
as well as Views\MainToolbar.js

?? Shouldn't the MainToolbar.js have "localization" added as well?

**Comment by jbest84** [comment]
Removed Sage from MainToolbar.js https://github.com/Saleslogix/argos-saleslogix/commit/148b9e2ddd1e8ed60668875c8332b414333a1cab

**Comment by rjledger** [comment]
Good.
