### ISSUE TITLE
SData HTML5 Mobile Web App - Activity Scheduling - Opportunity Selection issue/bug

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#15]
Mobile Web app is not allowing me to select an Opportunity from an Account that does not match the Account Selected.

The Windows/LAN and web do.

There's nothing wrong w/pre-filtering to the selected Account (Windows/LAN and Web do).. but you should be able to query another or click on select w/a blank and get them all (Opportunities).

FYI - Ticket selection works "right".

x-posted to teh Community

**Comment by jhershauer** [comment]
Hi RJ,
When you click on the Opportunity "Related Items" from an Account, this is the equivalent of looking at the Opportunity "Tab" on the Account Main View in the other clients. We do NOT allow you to see all Opportunities from this view.

It sounds like there might be a bug with Tickets. We'll look into this.

Now that you bring it up, though, it might be nice to see some kind of indicator on the list view that you're in a filtered view. Also, perhaps we could have a way for you to quickly go to "All <whatever related entity you're viewing>"

[Edit]: Oh...I just read the subject line, which changes the context of what you are saying. you want to be able to schedule an Activity for Account X and Opportunity Y, in which Opp Y is not related to Account X? Why would you do that?

Thanks!

**Comment by rjledger** [comment]
Jeff,
 I was on the Calendar and clicked on Add (+) to add an activity. This is a typical thing to do. One gets a phone call/email.. checks their calendar and adds an activity right then. It's got nothing to do w/"related". .. and the "tickets" thing is working right at that time.. we just need the opportunity selection to work like tickets.

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Jeff,
 There's a bunch of things related to activity work-flow that needs to be looked at. For instance.. when one is on an activity, one should be able to have a quick action to make a call right then. It would need to show ("pop up") a list of all the contact's phone numbers so you could choose. Once finished, you should still be on that activity and be able to complete it.

I'm finding one wants to and needs to use "mobile crm" a lot different than they do the Windows/LAN or Web client. It's really all focused around calendar/activity.. and calling/emailing. 

FYI: I picked (and got assigned to) the Mobile Roadmap as the area that I would be looking at/addressing in the BPAC Product Committee from last week.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
With regards to selecting an Opportunity when creating an Activity, I agree that it is a bit too strict right now. I think we should allow you to select an Opportunity without selecting an Account first. This will let you pick from the full Opportunity list. 

However, if you select an Account first, it seems like it should still filter Opportunities to that Account.

I think we also need to add a "None" option on lookups like we did with picklists, so you can "undo" a selection. We'll update this a bit for 8.0.

Thanks,
Jeff

**Comment by rjledger** [comment]
It currently allows you to select any opportunity first. The point I'm trying to make is that is does not work like Windows/LAN or the web because it does not allow selecting any opportunity after an account is selected. It just does not work like the other client apps.. which have been working the way they do "forever".

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
Well, not for me on v1.1. Attempting to select an Opportunity first results in an Alert that you must select an Account value first.

Anyway, I see what you're talking about with the pre-filtered list, combined with the ability to override that and do a fresh search on all Opportunities. We'll take a look, but as you pointed out, Mobile CRM is different, and not all features and flow are going to match up 100%.

**Comment by rjledger** [comment]
Remember.. I'm using the latest w/the Calendar updates. It works the way I described.
Can't use 1.1 - it's too restrictive.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jbest84** [comment]
Ability to remove associated entities from the activity was logged internally to 
INFORCRM-8550
