### ISSUE TITLE
Latest source (2011 09 23) - Adding an event defaults to today no matter what day picked in calendar

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#16]
A - Thanks for adding Events! Really helps to round out calendar/activities.

B - If you are on calendar and have a date picked other than today.. say labor day (Sept 5) - adding an event id defaulting to today rather than the picked date. All other "activities" follow the "picked date" correctly.

C - After adding an event it is not refreshing the calendar like adding any of the "normal" activities do.. SO it does not show up until you either browser refresh or move to week (or day) and then back to month.

D - Icon for Event  (in list) does not show up if you click on week.

E - Events are not necessarily all day things - they can be half days (ex:1/2 day conference that starts at 9am and ends at 12:00 noon.).

**Comment by wskidmore** [comment]
Sorry about that - the date should carry over when you are adding a new event now.

**Comment by rjledger** [comment]
No big deal....
I'm updating my post so you will see some additional comments - Would appreciate your thoughts about them.

It's 7:49pm edt here and it's 75 deg w/70% humidity... UGH! 

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
The event stuff is just basic functionality at the moment, there are still some design decisions to be made -- like tieing the icon to the event type (which would limit the number of available event types - I just added some basic ones as I couldn't find a set list anywhere). So right now all events use the same icon.

As for the the time, it shows the time in the event detail view, maybe I could put the times in the other views... was just trying to keep it short for mobile viewing but maybe I can work something out.

**Comment by rjledger** [comment]
Yep.. I fully recognize it's the basic stuff.. and it's very usable in a real world production environment. 
The issue of Event type icon is definitely something that could get messy... I was thinking about a generic event type icon. I found one on the net that might be a reasonable fit. Will send it if you like.

As a former development manager and director on large scale control systems, I fully appreciate you guys being receptive to (all of) us submitting "bug reports" even though the code is still in development. The earlier we all find them.. the cheaper it is to fix them ;-)

FY: We not only are a BP but we run our business on SalesLogix every day and have so since we started years ago. What I've been doing is running basic tests against a dev/eval Slx "standard" db and then moving it into our production world. It's there we really find out if there are any issues (ex: data problems, etc) as well a get a good feel for usability before we even think about bringing it to our customers. 

Again - THANKS for the great work you guys are doing on "mobile".

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Oops.. took the event additions and brought them over to our production - now no longer can see anything at the "month" level except events. No normal activities. Week/day are fine - any ideas?

**Comment by wskidmore** [comment]
Shows up okay on the test database (which I believe is updated to 7.5.4 ?) - it does make two requests and the events load very quickly. So if it's going slower than normal you would see all the events load up, and 5-10 seconds later all the activities. That's for a month with maybe 10 activities, I'm sure if there is a lot of activities it may take more processing/loading time.

If still a no go after waiting, I'd check the two GET requests and make sure they are both coming back okay (not a server issue). Otherwise, it's something in the processFeed area that I will take a double look at.

**Comment by rjledger** [comment]
It looks ok against the 7.5.4 eval db.. but just not working against our production 7.5.4.

It just says "no records" for Monday Sept 26, 2011.
No counts showing for any days for sept except the event (labor day 5th....)

Was fine until I merged in these event changes. Tried cache flush.. iisreset, etc.. no go.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
To add..no errors show up in Firebug as well.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
For now I would just roll back to the older version. I know there was some changes in sdata in the upgrade which is probably the issue. ProcessFeed() is overridden in month view and the results of which is passed to the counts / day preview at the bottom - so it is probably a difference in how the sdata json feed is being returned and (not) processed.

**Comment by rjledger** [comment]
Found it!.. looks like you had hard-coded the "getActivityQuery" function in MonthView.js to user 'ADMIN' and had commented out the "user"... ;-)

Removed your "hard-code and it's working fine.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
Ah yes, sorry, we had tried a quick server upgrade and it caused the normal 'user' to not have certain privileges, so I had hard coded ADMIN while they worked that issue out. I just pushed up the non-commented out part also.

**Comment by rjledger** [comment]
Happens... to all of us a one time or another..
Just glad I found it quickly!
Thanks for the update.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
