### ISSUE TITLE
2.2 Quick Action Question

### ISSUE THREAD

**Issue by beckiblackburn** [Saleslogix/argos-saleslogix#162]
I have a need to create a 'submit for approval' quick action on a custom entity's detail view, that simply updates a status field on the record and then refreshes the detail view. I realize that all of the 'update' code is inside of the edit view and not necessarily readily available on a detail view. Is there an easy way to simply add a "click here to update one field in the record and Save" from a detail view? Do I need to copy a bunch of the code out of the argos-sdk\Edit.js and add it to my detail view in order to process the change I want? 

I know I could have them change the status field on the 'edit' view, but I would really like to handle it as a quick action if possible. If it's really not an easy task though from the detail view, then I will go that route, but I thought I'd pose the question to see if it was maybe not that difficult.

Thanks,
Becki

**Comment by jbest84** [comment]
You shouldn't need to copy any code. You can access the edit functions createRequest prototype via: `Sage.Platform.Mobile.Edit.prototype.createRequest` You should be able to use this to create your own sdata request and update whatever you need to.

**Comment by beckiblackburn** [comment]
Ah. That makes sense. I knew it had to be easier than what I was trying to do. It's Friday, and it's been a long week, so I think my brain got tired.

Thanks Jason!!

**Comment by jbest84** [comment]
You are welcome. Have a great weekend!

**Comment by beckiblackburn** [comment]
Did this even easier than that - just said 

```
var request = new Sage.SData.Client.SDataSingleResourceRequest(this.getService());
```

and then added the desired data to the request. Works great! :-)
