### ISSUE TITLE
2.3 - Latest develop code - Adding an Activity - MyActivities broken

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#166]
When I pick either the Account or Contact Lookup Control it give me the appropriate list.. BUT the "icon" on the top right is gray'd out and I cannot "search" - ??

Same issue adding an activity in Calendar, or on any other entity that uses/adds Activities.

**Comment by rjledger** [comment]
Added info.. there's something in general associated w/doing lookups to "add stuff" that is broken. I did a full retest w/both source as well as using the "gist", building and deploying.. no joy.

**Comment by jbest84** [comment]
@rjledger It looks like the issue is the right context menu is not loaded correctly on lookup fields. I have a fix incoming.

**Comment by rjledger** [comment]
Glad to have been of assistance... Works great!
If we keep knocking off these "bugs".. I'll not have a lot to do when the "beta testing" officially starts ;-)

**Comment by jperona** [comment]
Thanks for the testing RJ

On Thursday, August 22, 2013, RJ Ledger wrote:

> Glad to have been of assistance... Works great!
> If we keep knocking off these "bugs".. I'll not have a lot to do when the
> "beta testing" officially starts ;-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Saleslogix/argos-saleslogix/issues/166#issuecomment-23123735
> .

## 

Thanks,
John

**Comment by rjledger** [comment]
@jperona - you are welcome!
