### ISSUE TITLE
2.3 - change to using "moment" - causes customs to "break"

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#169]
Just ran into a situation where a custom module worked just fine for 2.2 (and down) and now displays a "bad format" on an datetime edit control in a custom Edit.js

Ideas/hints?

**Comment by jbest84** [comment]
What is the format string? Moment uses slightly different format strings than datejs did:
http://momentjs.com/docs/#/displaying/format/

I left datejs in the libraries folder, so if you don't want to port your code, you can just include datejs back in (not recommended). The problem with datejs is it monkey patches the native Date object, making it more difficult to find it's usage. Moment is AMD compatible, has a huge following, and is usable outside the browser (nodejs). Their docs are excellent as well!

**Comment by rjledger** [comment]
I made the change:
   was:
         startingFormatText : 'M/d/yyyy h:mm tt',
         completedFormatText: 'M/d/yyyy h:mm tt',
   now:
          startingFormatText : 'M/D/YYYY h:mm A',
          completedFormatText: 'M/D/YYYY h:mm A',

Suggest there be  note added indicating the possible "breakage".

Also.. noticed moment has TimeZone support - Both Web and Windows have a TZ lookup so that when you are scheduling an activity w/someone in another TZ you can set the date/time in the other TZ and have it reflect back properly in the UI.  Mobility needs this too.

**Comment by jbest84** [comment]
It will be noted in the 2.3 change doc. Thanks for the feedback.

**Comment by rjledger** [comment]
You are welcome
