### ISSUE TITLE
2.3 - A way to add (via custom module) to the Quick Actions on the "Home View"?

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#171]
Have not been successful in this area in the past and still not on 2.3. Customer(s) would like additional "Quick Actions" on home (as well as Detail views).

So far I've had to directly hack the home.js, etc.

Ideas/comments?

**Comment by rjledger** [comment]
.. additional info - the createLayout function in Home.js (file) takes a completely different approach than the way it's one has in a typical detail.js setup. Too bad there wasn't the same. Is there a good reason it is not?

**Comment by jbest84** [comment]
You do not have to hack any of our out of the box code to get this to work. In your application module, you can extend createLayout to include your own custom actions:

```
            var original = LeftDrawer.prototype.createLayout;
            lang.extend(LeftDrawer, {
                createLayout: function() {
                    var originalLayout = original.apply(this, arguments) || [];
                    originalLayout[0].children.unshift({
                        'name': 'CustomQuickAction',
                        'action': 'customAction',
                        'icon': 'content/images/icons/New_Contact_24x24.png',
                        'title': 'Custom Quick Action'
                    });
                    return originalLayout;
                },
                customAction: function() {
                    alert('custom action clicked.');
                }
            });
```

**Comment by rjledger** [comment]
"Almost" works.... I can get it to load my view but the left drawer stays "open" - ??

.. got it! - I think:
            if (view) {
               //view.show({insert: true});              <----Not this
               this.navigateToView(view);              <----Do this..
            }

Right??

**Comment by jbest84** [comment]
Right. insert: true is for inserting on an edit view.
