### ISSUE TITLE
2.3 - URL Attachments

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#174]
Attachments come in two types:
   a - File
   b - url

Windows/LAN & Web support both. Currently argos-saleslogix only allows you to upload a file attachment. argos-saleslogix will show you the url (text) if one is there - ex:
[InternetShortcut]
URL=http://www.saleslogix.com

However, there's no way to take "action".

So it's missing both the ability to create a url "attachment" as well as "launch" it.

**Comment by rjledger** [comment]
Just was looking at attachments and saw the "URL" stuff...

FYI - the hashTagQuery in attachment list.js expects DATATYPE to be NULL for a URL - not so.. 

In Windows/LAN created attachments - be they "normal" or a URL the datatype is always an "R".

This also fails the test in ViewAttachment.js _loadAttachmentView:

It is possible it has always been incorrect in Windows/LAN (forever)... and I did not check the web (app)...

I tested this by going into Windows/LAN and adding a URL - when I look at the attachment in mobility all I see is:
  [InternetShortcut]
  URL=http://www.saleslogix.com

If I load in a "shortcut" it will actually display the web page.

Kind of expected we would be able to "click" on the url (attachment) and have it actually open the page/item.

FYI - URL attachments are also used to point to all kinds of files - not just web pages.. for instance I know of a customer that has an extensive shared collection of documents on a server that his (url) shared out.. so his url could look like:
             \\servername\foldername\Mydoc.pdf
I'd expect to be able to click on this (and if the URL was accessible) have the pdf be displayed.

Very normal use case of a URL.

**Comment by rjledger** [comment]
Just verified.. even the Web sets the DATATYPE in ATTACHMENT as "R" (for ANY attachment/URL).

AFAIK (unless JP or PZ knows).. nobody knows what the "DATATYPE" really is used for. I don't know and I've worked on SLX since version 2.x ;-)

Just checked w/RJ Samp on it.. always an "R".. and nobody knows what it really does !

**Comment by jbest84** [comment]
What version for web? On mine it was setting dataType to NULL. Unfortunately there are some SData issues querying null against the URL field for some reason. I will dig into it a bit more.

**Comment by rjledger** [comment]
754….

I’ve gone back and checked and it has always put in an “R” no matter what. So I just tried it in Windows/LAN on 8.0…
And it’s an “R” for all types.. including a URL
  Did a typical url:
                www.rjlsystems.net
   and a “share” url:
                    \stargate\c$\temp\song.mp3

Interesting when I look at the attachment table.. the first has an extension of ".URL", the 2nd (the "share url") just ends in ".mp3 - as it should.

Both launch correctly in Windows/Lan 8.0 when clicked on in the attachment “tab” ;-)

So if it’s doing a NULL in the latest web (8.1?).. then the latest web has a bug.. it is broken.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047

**Comment by rjledger** [comment]
In ViewAttachment

 _loadAttachmentView: function(entry) {
            var data, am, isFile, url, viewNode, tpl, dl, description, attachmentid,fileType, self;

```
        am = new AttachmentManager();

        if (entry.dataType === "R") {                               <--------------------------
            description = entry.description; // + ' (' + entry.fileName + ')';
            fileType = Utility.getFileExtension(entry.fileName);
            isFile = true;
        } else {
            isFile = false;
            description = entry.description + ' (' + entry.url + ')';
            fileType = 'url';                                       <------------------------------------
        }
```

**Comment by jbest84** [comment]
@rjledger Fixed the viewing to check the url field.
