### ISSUE TITLE
Activity completion filling in RESULT but NOT filling in RESULTCODE - leaves a NULL

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#179]
A - Issue w/every release of mobility - including the "2.3"
A - Windows/LAN and Web both fill in this value correctly
B - The RESULTCODE is important to customers because they use this field in their reporting systems. If there's a NULL then the records are skipped

BACKGROUND:
Just had a customer complain that their weekly management reports were not showing all the meetings attended by their sales people. Any History records added (or Activity records "completed") by mobility users were not showing up. All LAN/web users were fine. Traced the difference to the RESULTCODE field in all Mobility related history records being NULL.

FYI - If you log into the LAN client as a user that has "bad" history records and open/OK one of those records, it automatically filled in the (correct) result code! Not an acceptable "fix" by the customer but proved the issue is in mobility.

So two things need fixing:
   1 - Adding a History record
   2 - Completing an Activity

If you guys can't fit this in (2.3) I'd sure like a pointer or two as to how I might properly hack it in for the customer - Thanks!

**Comment by rjledger** [comment]
Just did a quick look at the (argos-saleslogix) picklistField.js - unless I misunderstand how this control is working.. looks like it will need to be modified along w/the appropriate changes in Add a history record.. and complete an activity. 

We need to save both:
     Text -> (History)RESULT
     Code -> (History) RESULTCODE

Only saving  Text -> (History)RESULT right now :-(

**Comment by jbest84** [comment]
The web client sends the ResultCode as an empty string. Is this the expected behavior?

```
{
   "$name":"Complete",
   "request":{
      "entity":{
      ...
      },
      "userId":"UDEMOA00000I",
      "result":"Complete",
      "resultCode":"",
      "completeDate":"2013-09-05T17:08:47Z"
   }
}
```

**Comment by rjledger** [comment]
… bad.. I wonder if there is a back-end business rule that fills it in? – If not then the web is broken as well.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047

**Comment by jbest84** [comment]
No, I am checking my database. The RESULTCODE is empty in the HISTORY table when I complete it. I will check with the activities team and get back with you.

**Comment by rjledger** [comment]
Not good – The Windows/LAN client has always posted it.. for the past 15+ years  ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047

**Comment by rjledger** [comment]
Right from my production db:

H6UJ9A0001PY    V6UJ9A0001KZ    262145  A6UJ9A000018    NULL    NULL    rjlSystems, LLC NULL    NULL    NULL    NULL    2013-09-05 15:30:00.000 15  On Line Meeting NULL    NULL    F   NULL    NULL    U6UJ9A00000A    Ledger, Robert  2013-09-05 15:30:00.000 Complete    NULL    2013-09-05 15:27:23.000 U6UJ9A00000A    2013-09-05 15:29:48.000 U6UJ9A00000A    2013-09-05 15:29:40.000 U6UJ9A00000A    Test for ResultCode Test for ResultCode F   NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL
H6UJ9A0001PX    NULL    262145  A6UJ9A000018    C6UJ9A00002U    NULL    rjlSystems, LLC Ledger, Robert  NULL    NULL    NULL    2013-09-05 15:00:00.000 15  NULL    NULL    NULL    F   NULL    NULL    U6UJ9A00000A    Ledger, Robert  2013-09-05 15:04:00.000 Complete    COM 2013-09-05 15:08:48.000 U6UJ9A00000A    2013-09-05 15:08:48.000 U6UJ9A00000A    2013-09-05 15:03:38.000 U6UJ9A00000A    Test Note   Test Note   F   NULL    NULL    NULL    NULL    NULL    NULL    NULL    NULL

First one was from completing an activity via mobility (2.2)     Complete   NULL 
Second was from completing an activity via Windows/LAN client   Complete    COM

**Comment by rjledger** [comment]
FYI - Customers sometimes change the "text" in the picklists but the "code" is what they depend on.

**Comment by jbest84** [comment]
@rjledger Let me know how this fix works.

**Comment by rjledger** [comment]
Checking it out now .... worked just fine - Thanks!

Also.. see my comments and reply to JP please.

**Comment by jperona** [comment]
FYI, there is already an open defect that this should be handled in the SData handler.

Especially, if the ResultCode is inferred.

John Perona
Director Product R&D, Saleslogix
w: (480) 304-4331tel:480-555-1234   |   m: (602) 418-8701 tel:480-555-1234
john.perona@swiftpage.com   |   www.swiftpage.comhttp://swiftpage.com

Try Saleslogix for Free
http://crm.saleslogix.com/trial

**Comment by rjledger** [comment]
Thinking out loud…  “This fix” that you guys came up with does appear to work fine and probably makes it a lot easier to deal with custom situations..  does not require an SData update.. and can be easily retro-fitted to previous versions of mobility where RESULTCODE is impacting customers.

.. and Oh yes.. and serves as a possible model to where we can manipulate the use of a picklist to let us store both "Text" and "Code" for other situations.. and not tied to a particular entity ;-)

rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047

**Comment by jperona** [comment]
Sure, we'll review with the team but, custom scenarios could also be handled by using an onBeforeInsert rule, right?

**Comment by rjledger** [comment]
From my point of view.. I'd rather be doing this type of customization IN the mobility app in javascript - not at the business rules level which then impacts the whole web thing.

So far 100% of my customers using mobility are Windows/LAN customers (no web) so we only deploy what is needed to get mobility up an running (SData and Mobility portals ;-)

If I'm mistaken in my interpretation of your post - please correct me.

.. and yes, the fix works 100% right.. in fact, I was able to put it into a customer's 2.0 on 754 in just a couple of minutes (via WebStorm), build (using the gist approach) and deploy, and work 100% correctly.

**Comment by jperona** [comment]
So absolutely, the fix as applied to mobile is acceptable.  However, we want to ensure that the SData stack defaults the data in resultcode to the picklist value if it's not provided.  This way those who do not fill in the field get the appropriate value also.

Your deployment would work for this also and keeps the integrity of the system when using other integrations in our stack.

So you get the best of both.

**Comment by rjledger** [comment]
Sounds like a plan to me!
.. and thanks again to the team for coming thru in a pinch!

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047
