### ISSUE TITLE
In Calendar - Week View - Clicking on an Activity - Get error message

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#18]
Just discovered this ...

Returns:
    "The requested entry is not available."
for every activity. However, if it is an event, it DOES go to it ;-)

**Comment by wskidmore** [comment]
It was storing the $key with the ActivityId= in front, instead of just the $key itself. Should be fixed now.

**Comment by rjledger** [comment]
Great! I did take a look and thought that was it ;-)

Ques: I see a 1.2 beta fork has been started... is there a plan to move the changes that are in master into it?

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
No, the v1.2-beta-1 branch does not have Event support and several other enhancements. It was meant to be just a localization release for French, Italian, etc groups but we snuck in a few things like the hash tags in search, week view, quick select lists, etc. 

Sometime soon (possibly today) the dojo conversion branch will replace master, which has all the current Master features (well, I re-hauled the Calendar views) and has more new stuff coming soon.

**Comment by rjledger** [comment]
What about the bug fixes missing from beta?

Connected by DROID on Verizon Wireless

-----Original message-----

**Comment by wskidmore** [comment]
Beta was branched off around Sept 20 (?), just before we started adding Event support, which is where I see the other bugs coming from (issues in separating events vs activities and how the feed is different for each).

The only one I see is Issue #14: https://github.com/SageScottsdalePlatform/argos-saleslogix/issues/14

which doesn't appear to be fixed in any version.

**Comment by rjledger** [comment]
Bug in Ticket list.js, etc.. I'll look thru all the issues I've seen/reported and post back this evening. I know there were a few more.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
