### ISSUE TITLE
2.3 - Having a "failure w/"less"

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#184]
2 Errors:
FileError: 'http://gobidev8:3333/slxmobile23/source/products/argos-saleslogix/content/css/app.less' wasn't found (404)

FileError: 'http://gobidev8:3333/slxmobile23/source/argos-sdk/content/css/themes/swiftpage.less' wasn't found (404)

Seeing this when I try to run off the "source":
.../SlxMobile23/source/products/argos-saleslogix/index-dev.html

Do not see this if I do a "gist" build and run off the build.. Any idea as to what I may be missing/messed-up in the index-dev.html? .. it looked ok to me.

**Comment by jbest84** [comment]
If you are getting a 404 on .less files for dev, ensure you have a MIME type setup for it. If you are using IIS:

```
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension=".less" mimeType="text/css" />
        </staticContent>
    </system.webServer>
```

**Comment by jbest84** [comment]
I have updated the README to reflect this: https://github.com/Saleslogix/argos-saleslogix/commit/f7bedcc177b34214a9088ec0e7a01910bbede108

**Comment by rjledger** [comment]
ARGH! .. stupid ME!
Not enough coffee.. and a little to early for a beer!

Owe you big time (for this and others).. will connect up @Saleslogix Partner conf/BootCamp in Nov... 
.. and if you get a chance to get to NH - will give you a free ski/snowboard/snow-bike lesson
Thank you!

**Comment by jbest84** [comment]
No worries. I created a wiki page around themes that mentions the content type for .less files, but it should have been on the main README as well. (https://github.com/Saleslogix/argos-sdk/wiki/Creating-A-Theme)
