### ISSUE TITLE
The new "duration" control - NICE! (in dojo version)

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#21]
Really like the new duration control, I went ahead and replaced the reminder w/the same control to make the user experience cleaner.

Tests out just fine in both cases.

Really great to be able to put in exactly what you want (to the minute) on the duration (and alarm/alert) time(s). Now I have to figure out how to retrofit it in 1.x for our existing customers who want this type of user experience/gui from me yesterday ;-)

Oh yes, on FF there seemed to be a "line up issue" with the "box" and the list.

NOTE:
I suggest you probably want to come up with a more generic name for the control.. although what you would call it - I have no idea.

**Comment by jhershauer** [comment]
If you're talking about the one that was checked in a few days ago, it will be changing again (you'll still be able to enter an exact value), and we'll be updating the reminder to match.

The update will be an editable pick list control. You get a single text box to enter the time, or you can click the "…" to pick from the list of most used values. We'll auto-complete for you. 

For example:
"15" will be 15 minutes (default is minutes).
"15 min" will also be 15 minutes
"2 d" will be 2 days.
"2 da" will also be 2 days.

On Oct 27, 2011, at 5:50 PM, RJ Ledger wrote:

Really like the new duration control, I went ahead and replaced the reminder w/the same control to make the user experience cleaner.

Tests out just fine in both cases.

Really great to be able to put in exactly what you want (to the minute) on the duration (and alarm/alert) time(s). Now I have to figure out how to retrofit it in 1.x for our existing customers who want this type of user experience/gui from me yesterday ;-)

Oh yes, on FF there seemed to be a "line up issue" with the "box" and the list.

NOTE:
I suggest you probably want to come up with a more generic name for the control.. although what you would call it - I have no idea.

## 

Reply to this email directly or view it on GitHub:
https://github.com/SageScottsdalePlatform/argos-saleslogix/issues/21

**Comment by rjledger** [comment]
Yep... 
I like the approach you have described in your email (below). I had not tried the one that is up there on my smartphone (droidX) or droid pad (Samsung Galaxy 10.1) yet.... but was thinking it might be a bit "rough" for some folks on a small smartphone screen. What you describe you are going to do would be a lot easier to use.

2 h would be 2 hours?

Side issue... and probably the most important... what will be the impact to existing customs already deployed to customers on the 1.x platform? Will we have to "re-factor" them? If so, I need to build time into our quotes now to cover the additional time/effort. Customers do not like paying for a custom twice.. so if we can build in the costs up front it's a LOT easier.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Oh yes.. personal activity still requires an Account.. even though it's not supposed to.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Just noticed - When completing an Activity it is still using the "old" control for duration.

Frequently an activity may be shorter (or longer) in duration than was scheduled. It is VERY desirable to record the actual duration of the meeting. The "old" control will not let you do this.

**Comment by rjledger** [comment]
Thanks for the duration fix!
