### ISSUE TITLE
3.0 - working on 30_for_754 for John - loading issue

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#210]
The "Saleslogix" white on black top "banner" shows up but NO login view.

**Comment by jbest84** [comment]
Is this for development? Any errors appearing in the console?

**Comment by rjledger** [comment]
JohnP had asked (sent me an email) if I would be willing to "donate" my work on 22 & 30 for 754 becaues I have been able to bring over additional features from the 22 and 30 on "8" - I said yes... the 22 is ok - the 30 code "delayed loading" is just not working.  emailed him about it.. he said to post here so you guys could give me a pointer or two.

No errors show up in firebug.. zip .. nothing. No luck w/chrome either.

**Comment by jbest84** [comment]
In the SDK, when a view is registered (in Application.js), init is no longer called on it. Init is defered until it is requested (App.getView()). This delays the rendering and reduces the initial dom size significantly.

**Comment by rjledger** [comment]
I can see on an 8.0 (where it works) it's definitely a slower response.. and on my attempt to do it on 754.. nothing - blank.

**Comment by rjledger** [comment]
.. just ran thru a few things I (and my customers) always use.. calendar.. day/week/month - really slow on response compared to older versions of mobility.. I hope there's a plan to fix this. I could not work with this on my production.

Had an activity for "today".. clicked on week - nothing showed.. clicked on month.. it finally showed.. than back to week.. nothing.. then day.. to week and I saw it in triplicate. All this on an 8.0.

BUT back to the 754.. I'm going to hack the init back into Application.js - any suggestions?

**Comment by jbest84** [comment]
If you add init back and increase the DOM size, you will cause a severe performance problem on IOS7 Safari. There are issues with slow DOM access under the new IOS7 that causes edit screens to lock up for several seconds before you can focus a field.

**Comment by rjledger** [comment]
Happens that I don't use (or own) anything "apple" ;-) .. droid or ff/chrome on the desktop.
If the system is compromised for Apple.. it's useless to 90% of my customer base.

**Comment by jbest84** [comment]
The system is not compromised. The code to defer to the view rendering was written by myself as an experiment back at the end of July to reduce the overall DOM size (before IOS7 was on our radar). There is also code on that branch to delete a views rendering when it transitions away, we just aren't there yet, so we took the first part instead (the DOM will grow as you load more views). 

I did some initial work on my compatibility module. It is loading OK now (removing my attachments and my activities like it should). Here is the initial commit: https://github.com/Saleslogix/argos-saleslogix-20_for_754/commit/2d20c5d4434e0f56af5ac592686330534c4141e2

I put the changes on a 3.0 branch.

**Comment by rjledger** [comment]
Good.. You now have me pointed in the right direction.. I'm doing some "hacking" now and will post my results..
Also, the synopses on your loading changes really helps to fill in the blanks.

THANKS!

**Comment by jbest84** [comment]
No problem. I just pushed some more changes to get the calendars working with moment.js: https://github.com/Saleslogix/argos-saleslogix-20_for_754/commit/4d3b5bc567af4049dd2b757951db0a553188da6e

**Comment by rjledger** [comment]
Thanks again!.
I’ll pick up those changes as I work thru my updates.
rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
