### ISSUE TITLE
3.0.x - Cannot select multiple hash tags.. and cannot add in additional query info

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#214]
Hashtagging supports the concept of multiple (contcatonated) hash tags so that users can quickly "filter" their data.
  ex: on accounts
      #cust #my rjl
This would select all accounts where the type is customer, logged in user is the account manager and the accounts start with rjl

The Right Drawer does not let you pick multiple tags (OOTB or custom (3.0.1))  etc.

**Comment by jbest84** [comment]
You can still type in multiple hashtags. We have your feedback recorded from a previous sprint review, we just did not have the time to go ahead with the changes.

**Comment by rjledger** [comment]
Yes you can.. but w/the long hash tags names you guys have for OOTB it’s really a non-productive scenario.

All of my customers use hash tags. Every customization we do includes hash tags.. so I’m going to redesign the search/lookup to accommodate multiple tag selection. Otherwise there’s not a single customer I can move over to 3.x… It’s a revenue issue for me (and all partners)..  I’ll not make the code changes available (unless someone wants to pay me) since its 100% out of my pocket to do it.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by rjledger** [comment]
I just saw the "custom" for multiple-select hash tags (in the argos-sample) - not too bad ;-)
Tried it out.. it's definitely something we can work with - THANKS!

From a productivity (fewer clicks) in the end the "multi-select" should happen when you have the right-side open.. and then click on lookup. Is there a way I could override the "auto-close" on the hash tag "pick"?
