### ISSUE TITLE
3.0.1 - Adding Activity to lead vrs Contact acts differently

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#216]
A - On a contact - Add an activity
    1 - Contact/Account names pre-filled - Correct
    2 - Contact's Work Phone pre-filled - Correct

B - On a Lead - Add an Activity only works correctly IF you are ON the lead and using the "releated" Activity
  All others fail (Quick Action and List/Immediate Action)
    1 - for Lead says NO - Should be yes
    2 - Lead/Company data missing - should be pre-filled
    3 - Lead's phone missing

**Comment by jbest84** [comment]
Can't reproduce this on latest
