### ISSUE TITLE
Latest dojo based customs using argos-sample - having failures

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#22]
At BootCamp we ran against an 8.0 db and I also repeated the same when I got back in the office. using the same vm - all seemed well.

When I tried to run the latest argos-saleslogix and argos-sdk with the argos-sample (latest) using the following scenario(s):
    A - same 8.0 VM - all ok
    B - Ran the SAME against SalesLogix v7.5.4 (fall-back mode) - all of the "row" related customs "fail". No errors are thrown or seen in FF FireBug. All that happens is the custom "overrides" do not happen at all. 
   EX:
                  //Add Region to the Account Detail view, right above the Type property
            this.registerCustomization('detail', 'account_detail', {
                at: function(row) { return row.name == 'Type'; },
                type: 'insert',
                where: 'before',
                value: {
                    name: 'Region',
                    label: this.regionText
                }
            });

just does not happen in 7.5.4

Oh yes, I know about the "name" -> property change and I tried it.. still failed.

**Comment by jhershauer** [comment]
I'm not sure what the DB version would have to do with that particular problem. Are you sure you're not trying to create your custom module using the new code, and applying it to a v1.1 mobile portal on your v7.5.4 environment? That's not what we mean by fall-back mode. 7.5.4 DB support would still require that the mobile App and Customizations be of the same generation.

Granted, we made a lot of changes last week and there might still be some clean-up to do. We'll definitely test out the customization scenarios.

Thanks,
Jeff

**Comment by rjledger** [comment]
Hi Jeff,
  A - I updated the "dojo" based code (sdk/saleslogix, and sample) to the latest and tested it on the v8.0 image from BootCamp - all was fine - all customs working.

  B- copied the dojo based mobile from my v8.0 system to my existing 7.5.4 dev system

  C - the OOTB dojo mobile worked fine (did a "fall-back" ok)

  D - Started to run thru the customs in the sample and found the "problem"... some working, some not but NO errors showing up in FireBug. Was able t track it down to all customs that did an "insert/modify", etc that were attempting to modify a "row" failed.. everyone of them. All the others seem ok.

I have tried a couple of things (the name->parent change) but zero success. Ideas I can try?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
To add.. Quick Actions as well "failed".

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Just checked - the Account "localization" worked.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
I'm not getting any row level customizations using the latest code. This is partly due to the new Detail/Edit layout structure as the "row" in the at() function is the entire "section" object instead of an individual row object. 

I've brought it up with the others and we are discussing different approaches to address it at the SDK level.

**Comment by rjledger** [comment]
Great!  I was starting to think I was going nutz ;-)

Once you guys have an idea, etc.. please let me know and I'll be glad to be a guinea pig to test it on 7.5.4 as well as 8.

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Kewl, I was going bonkers this weekend.....never could get stuff to work.

RJ Samp
Sr. SalesLogix Developer
Doextra Corporation
www.doextra.com
630.561.3249

-----Original Message-----
From: Robert Ledger [mailto:RJLedger@rjlsystems.net]
Sent: Mon 11/14/11 5:30 PM
To: Tony Skidmore
Subject: RE: [argos-saleslogix] Latest dojo based customs using argos-sample - having failures (#22)

Great!  I was starting to think I was going nutz ;-)

Once you guys have an idea, etc.. please let me know and I'll be glad to be a guinea pig to test it on 7.5.4 as well as 8.

rjl

## 

RJLedger - www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Latest update on _CustomizationMixin.js in the sdk by Morty seems to have done the trick!

Question.. should we use "property" or "name" in our customs?

**Comment by jhershauer** [comment]
Hi RJ,
You will actually see both Name and Property on our out-of-the-box views. Best practice is to use Property to identify the property in the JSON Entry that you want to bind to. Name is now the name of the field in the view (more of an identifier). Now, when you have a property being bound multiple times on a view (such as in the Detail pane AND in the Quick Action pane), you will see the same property name twice, but different "Names" applied to the fields, giving you a unique value to reference in your customizations.

We will also be adding a Name property to the sections, so that you can reference those when adding a customization.

**Comment by rjledger** [comment]
Very Nice!
Thanks Jeff (and team).

I have a side issue related to security that I'd like to have a 5 minute discussion with you. I wished this had come up at Bootcamp.. but it came up in a discussion w/a client today and I believe it would be very useful (and easy to implement).

Can I give you a quick call (phone)?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
