### ISSUE TITLE
PDF's not displaying in Mobility 3.0.2 on 8.0 or 8.1 on Android devices

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#231]
Basically the same issue as #222 - but now I'm getting major complaints from customers. My response is... I've passed this to the Saleslogix team and so far no response.

I've seen this problem at a a couple of customer sites on ALL their droids.. as well as on my own production and dev/demo site.

txt attachments, images ok.. blank on pdf's

iOS device is displaying.. but NO zoom capability.

Really need a way to fix this asap - thanks. rjl

**Comment by jbest84** [comment]
Is a PDF reader installed on the device? What browser are you using? What version of Android? Can you try this commit and open the pdf in a new window: https://github.com/Saleslogix/argos-saleslogix/commit/99d88f44c037aab0701399a0b231ddbdb85d6482

**Comment by rjledger** [comment]
Thanks Jason,
As far as a PDF reader is concerned.. I’ve got the quickoffice, kindle reader, and docusign.. all read a pdf.

Tried the ‘droid browser.. and FF .. both “failed”

   I’ve got to jump out for a few hours to teach a few (Alpine) ski lessons – as soon as I get back this evening I’ll give the changes  a shot!

## rjl

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by jbest84** [comment]
Also - We have updated the 754 compat module for the upcoming 3.0.3 release. Do you currently use the batch scripts to deploy this out? It looks like an AA bundle 8.x style is not possible, as 7.5.4 is hardcoded to build only argos-saleslogix and argos-sdk. Would a pre-built zip file be useful?

**Comment by rjledger** [comment]
Making the changes for the pdf attachments resulted in hanging the FF browser on the desktop. The doc opened IN the mobile window and clicking on the button did nothing.

On the 754 compat - I do not use any scripts to deploy.. do it manually and completely outside of AA of course. Also my 754 compat is quite different from what you guys use.. I have a myActivities, etc... and use this w/all my customers.. don't use yours at all.

**Comment by rjledger** [comment]
OK.. we are displaying in an external window now (as well as in the iFrame ;-) on FF on the desktop.

Tried on droid tablet w/OOTB browser - no go - crashed browser when I hot the "button"

Tried on droid w/chrome browser... started to work.. saw download complete - pressed button - another window opened.. then finally crashed.

Tried on droid w/FF browser -  nt so good there either.

**Comment by rjledger** [comment]
Any update on this?? - I've got a couple of very un-happy customers beating on me...

**Comment by jbest84** [comment]
Our QA is reporting that if you click on a PDF under chrome/android it will download the file, not display it in the browser. I just verified this on our Samsung S4, android 4.4 by downloading the file and opening it from downloads. Unfortunately it appears the native android browser does not render or download the PDF even though it gives you a message that it is downloading a file.

**Comment by rjledger** [comment]
Correct! This is what my customers (and I) have been experiencing.

We can not get it to work on FF or Chrome (add-on) browsers on Android either.

So what do we do?

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by rjledger** [comment]
Had submitted this as a bug during "official" 3.0.3 beta testing.. status??

**Comment by jbest84** [comment]
We were not able to reproduce the issue you are seeing in Chrome. On our Samsung S4 and Nexus 7 using Chrome, we are able to download the file and open the PDF. This works for smaller files (100's of KB) and larger files (several MB). The OOTB browser is buggy displaying Data URI's, we will need to document that as a known issue.

**Comment by rjledger** [comment]
Definitely fails on my Droid X w/OOTB Browser, Chrome, and FF.. and on a customer’s environment (devices)  the same issue.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by rjledger** [comment]
Just did a bit of searching on the net on the subject of pdf and droid.. and there seems to be a lot of issues out there in general. One thing that was clear - openURL() works on iOS.. not on droid..
also: http://www.sencha.com/forum/showthread.php?239388

Interesting stuff:
https://github.com/mozilla/pdf.js

**Comment by jbest84** [comment]
Yeah there are a lot of issues. Windows Phone 8 was so bad we are forced to not support attachments on that device (couldn't display PDFs and images over 1MB were crashing the browser). It has been a while since I have looked at pdf.js, I will check it out more today and see if there is anything we can do here that will give us a more consistent experience across devices.

**Comment by rjledger** [comment]
Yep.. saw that 8 was a problem  - not surprised ;-)

.. I tried some more tests on my droidX and the Samsung  (tablet) – no joy ☹

## Hopefully pdf.js will help

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by rjledger** [comment]
Any progress on the pdf on droid issue?.. Customers looking for answers and I had to tell them that the newest release (3.0.3) is still "broken" - they are not happy :-(

**Comment by jbest84** [comment]
Can you try this patch: https://github.com/Saleslogix/argos-saleslogix/compare/develop...topic-attachments

It uses a blob URL instead of a data URI. The native browser does not work with this change, but chrome appears to be working OK for me (same as data URI).

**Comment by rjledger** [comment]
Tried it on my droid tablet w/chrome… clicking on open in new window just  flashed a tab.. and it went away leaving the blank one…  no joy..
rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by jbest84** [comment]
Right, it should be downloading the file not displaying it in the browser. Can you check your downloads and see if the file is there.

**Comment by rjledger** [comment]
Yes it is downloading… and I can “force” it to load up in my adobe reader…

QUES:
    What is the difference between a word doc downloading and a pdf downloading??
When a word doc downloads I get a “prompt” to open it up in an app.. but not so w/a pdf. If pdf’s downloaded and prompted like a word doc (or ppt, excel, etc) then it would be the ideal solution to the problem. – What do you think?
rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by rjledger** [comment]
Do we have any possible resolution to this problem?

**Comment by gitCHenrie** [comment]
The browser takes over and determines if there is a application that can be used top open, and if not is simply down loads it.  So different browsers will be have differently as to IE, Safari, Chrome, Fire fox and depending on what OS they are running on. For example Safari on IOS behaves differently than on the OSX etc..

**Comment by rjledger** [comment]
Yep.. works on desktops and on simulator/emulators…    However.. on real Apple and Android devices… it fails  to do so.. and it’s not just me.. it’s 100% of my customers.

Right now (including version 3.0.3) we have a “broken” situation w/real mobile devices. Customers keep asking when this will be “fixed”.. my answer is .. I have NO idea.. if ever.

We need this fixed.. it’s more important to customers than groups, etc.. we need a mobility product that id “defect free”.. Not more functionality.

If someone would like to talk w/me directly.. just call ( +1 603.369.4987.. and punch 0)

rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by jbest84** [comment]
We test on _real_ devices and do not use emulators or simulators. We are not able to reproduce this behavior. Here is my reply from April 4th:

"We were not able to reproduce the issue you are seeing in Chrome. On our Samsung S4 and Nexus 7 using Chrome, we are able to download the file and open the PDF. This works for smaller files (100's of KB) and larger files (several MB). The OOTB browser is buggy displaying Data URI's, we will need to document that as a known issue."

**Comment by gitCHenrie** [comment]
I'm a little confused.
You stated that this:
 "Yes it is downloading… and I can “force” it to load up in my adobe reader…"
And now you are saying that it is broken for 100% of your customers.

You asked what the difference was for docs. and pdfs. and the differences is that the browser is in control of how it determines to open or view the file.

So yes it is not Ideal that the file downloads and then you have to  Manually open it with the the PDF application and  unfortunately this is a limitation of the browser in which we are not happy about either. Hopefully as the mobile browsers evolve this will get better, and of course we are always looking at ways to solve this problem.

Or are you saying that the pdf is not downloading and you can not view it manually so that is th e case that would be a defect, in which we can not reproduce  with our native non simulated deceives. 

So what is the real issue. is it they do no like the way it works?

Cam

**Comment by rjledger** [comment]
Here’s a test I just ran on my Samsung Galaxy tab w/303:
   A - .jpg <--- downloads/displays fine
   B - .txt <-- downloads/displays just fine
   C - .pdf <-- starts to show the “downloading busy”.. and then “crashes”

Get the same results on my DroidX phone

Doing both over (local) WiFi in the office.

rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by rjledger** [comment]
On the Samsung tablet:
  I did the last test using the “native” droid browser.. If I use the Chrome (add on) one.. the pdf downloads.. then I have to go looking for it to display it.
  If I use the FF browser (add on) .. it’s now displaying a reader w/the pdf IN the window… this is new.. and it probably has something to do w/the latest FF for droids..

So it looks like the “native” droid browser is a looser.. and not to be used.

## rjl

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by gitCHenrie** [comment]
I think Jason stated that the Native Browser does not work, but chrome/android does. which was a know issue.

"Our QA is reporting that if you click on a PDF under chrome/android it will download the file, not display it in the browser. I just verified this on our Samsung S4, android 4.4 by downloading the file and opening it from downloads. Unfortunately it appears the native android browser does not render or download the PDF even though it gives you a message that it is downloading a file."

So, I you are okay now and every thing is working as expected, all thought not to your liking right?

**Comment by rjledger** [comment]
I’m ok… but agree it’s a nasty situation.

However I do suggest that there be a notice put out on Mobility about this. 99.9% of the folks out there using it are not aware of any of this.. they need to know.. and I include partners as well – BIG TIME ;-)

FYI – Chrome/FF were acting the same a little while ago.. but FF did upgrade and I’d suggest FF is the browser way to go over Chrome… and “native” – forget it..

They also need to know they will HAVE to upgrade to 3.0.3 to get it to work “this good” ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by gitCHenrie** [comment]
You know that we officially only support the following for attachments types, because of the inherit problem with the mobile browsers and view documents with the in the OS. From the Install docs under whats new.

"attachment using Lookups, searching through a list of attachments, and opening an
attachment associated to a Sage SalesLogix record. The supported attachment types are
PNG, BMP, TIF, GIF, and JPEG, but your ability to view will be determined by the viewers
available on your device."

So Fire Fox for Android has solved your Issue but we do not officially support  FF for Mobile so there coudl be issues with it, that we are not a ware of.

Thanks

**Comment by jbest84** [comment]
Mobile 4.0 now uses the pdf.js project to render the PDF within mobile.
