### ISSUE TITLE
Unable to run 3.0.2 or 3.0.3 in debug mode - development environment appears broken

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#235]
As part of normal development/test of custom modules, it has been possible to run off the "source" when it has been deployed to the mobility web site.
  ex: http://hostname:3333/slxmobile/source/products/argos-saleslogix/index-dev.html

This is no longer working - it throws errors and we don't even get a login view.

FYI - I did make appropriate changes to the config development.js as I've always done in the past (also it will not work OOTB either) - also tried a version of index-dev.html w/the "extra stuff" stripped out of the "body" part - still failed w/server error..

IIS Log errors::
2014-03-27 11:51:07 192.168.1.109 GET /slxmobile303a/source/products/argos-saleslogix/index-hack.html - 3333 - 192.168.1.101 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+rv:27.0)+Gecko/20100101+Firefox/27.0 500 19 183 209
2014-03-27 11:51:45 192.168.1.109 GET /slxmobile303a/source/products/argos-saleslogix/unsupported.html - 3333 - 192.168.1.101 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+rv:27.0)+Gecko/20100101+Firefox/27.0 500 19 183 203

**Comment by jbest84** [comment]
What client side errors are you getting? Where is the source coming from? What are you trying to accomplish? Debug mode would be loading the uncompressed files in a built environment (using index.*), development mode would be loading from source (using index-dev.*).

**Comment by rjledger** [comment]
## The page cannot be displayed because an internal server error has occurred.

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by jbest84** [comment]
You should not be getting a server error loading an .html page. There is no server side processing done on it, it is a static resource. Perhaps this is an IIS configuration issue.

**Comment by rjledger** [comment]
Created a simple myTest.html file that just displays a message "Hello"..
When it is in:
 http://hostname:3333/slxmobile/source/products/argos-saleslogix/myTest.html
I get an error:
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.

It's NOT happy about the 
    ....Config Error    Cannot add duplicate collection entry of type 'mimeMap' with unique key attribute 'fileExtension' set to '.less'
Config File \?\C:\inetpub\wwwroot\Saleslogix\SlxMobile303a\source\products\argos-saleslogix\web.config

**Comment by jbest84** [comment]
I am guessing SlxMobile303a has a web.config in it as well? The child web.config in the source\products\argos-saleslogix folder will inherit form the parent. Either move the source to a different folder, or change the source/parents web.config and remove the mime type for less.

**Comment by rjledger** [comment]
AH-HA!
I was suspecting this was the issue.. but wanted to get it confirmed by the “experts” ;-)

I’ll test over the weekend and let you know how it goes (vi GH).
Thank you!

## rjl

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454
