### ISSUE TITLE
3.0x - DateTime picker shows wrong 'day' for timeless activities

### ISSUE THREAD

**Issue by beckiblackburn** [Saleslogix/argos-saleslogix#237]
If you are scheduling an activity, and choose timeless, when you go to change the start date, you'll see April 1 (for example) which should be a Tuesday, but it displays as 'Monday'. See screenshot. This is the mobile version from 8.1 OOTB - perhaps this is already fixed, so if it is, let me know. Thanks!!
![screenshot_mobiledatepickerissue](https://cloud.githubusercontent.com/assets/459620/2595568/2b5459f4-ba9c-11e3-9083-60d19cd86f75.jpg)

**Comment by rjledger** [comment]
Point Of Information:
    “Timeless” should always be set to 5 seconds after midnight on the “timeless” day.
EX - If I were to set a Timeless for today it would be:  20140402 00:00:05

The system requires special handling of the 5 seconds after midnight value in the DateTime “conversion”.. there’s a special indicator for this DateTime “type” and it is “Z” in the SECTABLEDEFS.DATETIMETYPE field    ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by beckiblackburn** [comment]
Agreed, RJ. But "Timeless for today it would be: 20140402 00:00:05" is then converting that to x hours back (since the US is behind GMT by 5-8 hours, for example) and then shows the 'day' as yesterday, by name, even though the date is today. It stores the date correctly - but the picker is confusing as it shows the name of the day for the day before the actual date. Does this make sense?  I never noticed it before, until a customer complained about it yesterday.

**Comment by jbest84** [comment]
@beckiblackburn We have a "partial" fix for this in 3.0.3. The date picker is still wrong in 3.0.3, but the edit view works correctly when repeatedly toggling the timeless button. I have added your defect to our 3.1 sprint.

**Comment by jbest84** [comment]
https://github.com/Saleslogix/argos-saleslogix/commit/a58ffe612b12bbd3b028fa48f8f4f0f8d5ca7b5b

**Comment by jbest84** [comment]
SDK Fix: https://github.com/Saleslogix/argos-sdk/commit/bbb5ee0afd9fbb8c93824d54d2aaf76341378d4d

**Comment by beckiblackburn** [comment]
Ah, great Jason, thanks!!

**Comment by rjledger** [comment]
Yep.. and the convert back is the problem.. it’s ignoring the “5 second rule” .. and the fact it’s a “Z” type ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by jbest84** [comment]
Fixed in 3.0.4 and develop

https://github.com/Saleslogix/argos-sdk/commit/1d20947ced51f8471ca74c441b7a8aa1a722dfd1
