### ISSUE TITLE
SData Feed issue w/userOptions?

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#24]
Looking at home.js I see:
   userOptionsToRequest: [....]

Are these coming from UserOptionDef or UserOptions (by userid?)

Just do not see the exposed Sdata feed for UserOptions - only see UserOptionDef data returned.

Want to add a new UserOption to "query" on login and it just does not show up.... tested the SData feed and it's not there.. only seeing UserOptionDef data.

**Comment by jhershauer** [comment]
RJ - the UserOption query is going through the "system" useroptions endpoint, which should be a composite of the UserOptionsDef and UserOptions tables.

If you want additional User Options to be added to App.context.userOptions, then you can add entries to the userOptionsToRequest array (found in Application.js) in your custom module.

If the system endpoint is not providing the proper values, we might need to look at that on the SData side.

**Comment by rjledger** [comment]
I thought so... got some info on that from the white paper up on the support site in SData Endpoints.

I added a new record to UserOptionsDef and UserOptions (for the Admin user) :
    Category = "General"
    Name = "MobileWebAccess"
    Set the "values" to "T"
When using a direct URI to SData:
   http://localhost:3333/sdata/slx/system/-/userOptions?where=category eq 'General'
I inspected the payload for General:MobileWebAccess and got:
     Default Value = T
     And Value was "empty".

Did I do something incorrect?

FYI - I am constructing a method to control who can use Mobile Web for a client. They want to restrict it to just some of their users.

Thanks - rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Hi Jeff,
   Just ran a few more tests to be sure that SData was (or was not) returning the expected results.. and confirmed that there does seem to be an SData "issue" here.

I did a js alert popup that looks like (of course I did add it to userOptionsToRequest as well):
      var mwUser = new Boolean(userOptions['General,MobileWebUser']);
      alert(mwUser.toString());
and it displayed saying false... when there was a 'T' in the db for the (admin) user in UserOptions.

It would be great if we could use UserOptions for handling server-side central management of custom components, etc..

I was able to tap into the UserInfo table... but really do not want to add custom fields there to support the current project we are doing for one of our clients - rather use the UserOptionDef/UserOptions path.

Have you guys tested/verified this yet?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
I think you might have found a bug. I just checked out the UserOption code in Application.js, and it appears that we're only looking for the "value" in the user option entry. We should be falling back on "default" if there is no value.

I'll verify tomorrow and get a defect created if that's the case.

Thanks,
Jeff

On Nov 22, 2011, at 7:50 AM, RJ Ledger wrote:

Hi Jeff,
  Just ran a few more tests to be sure that SData was (or was not) returning the expected results.. and confirmed that there does seem to be an SData "issue" here.

I did a js alert popup that looks like (of course I did add it to userOptionsToRequest as well):
     var mwUser = new Boolean(userOptions['General,MobileWebUser']);
     alert(mwUser.toString());
and it displayed saying false... when there was a 'T' in the db for the (admin) user in UserOptions.

It would be great if we could use UserOptions for handling server-side central management of custom components, etc..

I was able to tap into the UserInfo table... but really do not want to add custom fields there to support the current project we are doing for one of our clients - rather use the UserOptionDef/UserOptions path.

Have you guys tested/verified this yet?

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
I did create both a UserOptionDef record and a UserOptions record. The def record had a 'T' in it and the options (for Admin userId) also had a 'T'.

When you do a "query" directly to the SData portal:
   http://localhost:3333/sdata/slx/system/-/userOptions?wherecategory eq 'General'
and look at the payload at General:MobileWebUser (my new one) you see:
     Default Value T
     Value          <---- nothing returned!
On other (OOTB) "Boolean" ones (ex: General:LookupAutoQuery) is see things like:
     Default Value F
     Value T

So I expected Default Value to come from the userOptionDef table and the "Value" to come from UserOptions... am I correct or not?

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
At the SData-level, it's working for me in the 8.0 environment. Although…the first time I tried it, I got the same result as you (nothing for Value). A few minutes later, after several re-tries, it showed up, though.

I haven't done enough research to see if this might have been a browser caching issue, a memcached issue, or what.

Have you tried for a non-Admin user? Are you seeing this for ALL options, or just the new one you created? Finally, did you verify that there are no mis-spellings or extra spaces in your UserOption record?

Thanks,
Jeff

On Nov 23, 2011, at 6:39 AM, RJ Ledger wrote:

I did create both a UserOptionDef record and a UserOptions record. The def record had a 'T' in it and the options (for Admin userId) also had a 'T'.

When you do a "query" directly to the SData portal:
  http://localhost:3333/sdata/slx/system/-/userOptions?wherecategory eq 'General'
and look at the payload at General:MobileWebUser (my new one) you see:
    Default Value T
    Value          <---- nothing returned!
On other (OOTB) "Boolean" ones (ex: General:LookupAutoQuery) is see things like:
    Default Value F
    Value T

So I expected Default Value to come from the userOptionDef table and the "Value" to come from UserOptions... am I correct or not?

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
A - Went back and checked spellings - Spellings all ok
B - IISreset and also stopped/started - no effect
C - fired up the chrome browser - connected to sdata - still the same - no value
D - Don't have memcached even installed on the test/dev system.

Create a UserOptions record for the user "lee" - It did show up in SData. However, if I flip the value, it seems to be caught in "caching" somewhere and does not show up immediately.

Looks like if the user is Admin, there seems to be a problem....
Q: Are you putting the Admin userId in as:
     'ADMIN'
   Or
      'ADMIN       '
I have tried both ways.. made no difference. No joy.

.. and would you not know it, the customer wants to "occasionally" block the admin user from using mobile..

Of course this is all being run on the current 7.5.4 released version.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Jason.. so are we (finally) going to see this (almost) 3 year old defect fixed?

**Comment by jbest84** [comment]
I tested this locally against an 8.4.04 system. I added three entries, one for USEROPTIONDEF and two for USEROPTIONS (one for admin, one for lee). The new option was MobileWebAccess, with a default value of T. Admin and lee both set this option to F:

For Admin:
`http://localhost/sdata/slx/system/-/userOptions?where=category%20eq%20%27General%27%20and%20name%20eq%20%27MobileWebAccess%27&format=json`

Returns correctly:
```json
{
      "$updated": "\/Date(1592380800000-0400)\/",
      "$key": "category=General;name=MobileWebAccess",
      "$url": "http://localhost/sdata/slx/system/-/userOptions('category=General;name=MobileWebAccess')",
      "$lookup": "http://localhost/sdata/slx/system/-/userOptions?format=json",
      "$httpStatus": 200,
      "$etag": "crIN9/AHj7A=",
      "$descriptor": "General:MobileWebAccess",
      "category": "General",
      "name": "MobileWebAccess",
      "displayName": "MobileWebAccess",
      "defaultValue": "T",
      "value": "F",
      "locked": false,
      "createDate": "\/Date(1592380800000-0400)\/",
      "createUser": "ADMIN       ",
      "modifyDate": "\/Date(1592380800000-0400)\/",
      "modifyUser": "ADMIN       "
    }
```

Same results with lee. Other users that do not have an entry in USEROPTIONS have a value of T in the payload, which is also correct. These values are cached in memory on the server (not in Memcache), so an IISRESET would be required if they are changed directly in the database. Otherwise, they would need to be updated via an SDATA PUT request.
