### ISSUE TITLE
in 3.0.3 Calendar has portrait/landscape reversed...

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#242]
In 3.0.3 on Android devices.. as well as FF & Chrome on eth desktop) the Monthly Calendar Portrait/Landscape views are "backwards..

That is - in all versions prior to 3.0.3 if the screen is Landscape, Activities/Events show on the RHS... in 3.0.3 it's on the bottom.. and if you go portrait - it shows (in 3.0.3) on the RHS!

So something got "broken" in 3.0.3..

**Comment by jbest84** [comment]
Fixed in https://github.com/Saleslogix/argos-sdk/commit/1a4435f89a83de0c8071e2739536fa607547d47e

**Comment by rjledger** [comment]
Patched it into my production.. and is fine... also it works in a 3.0.2 and does not break it ;-)
