### ISSUE TITLE
AddAccountContact onContactAddressChange doesn't work as expected

### ISSUE THREAD

**Issue by greensweater** [Saleslogix/argos-saleslogix#244]
This event handler is supposed to propagate the address to the Account section from the Contact section. It doesn't work because the null check on account.address will always fail on insert. Should be (line 115):

if (!this.fields['Address'].getValue() || !this.fields['Address'].getValue().Address1) {

**Comment by jbest84** [comment]
Thanks for the report. I committed a fix for this in our develop branch, which will be our next 3.1 release.
