### ISSUE TITLE
V3.0.3 (and prior versions) - Error in Ticket list.js

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#248]
If there is a NULL in the TICKET.CONTACTID an error is thrown and NO tickets are listed.

Not all customers set a Contact(ID) on a ticket - so the itemTemplate needs a "null" check" on $.Contact

**Comment by gitCHenrie** [comment]
I checked this out an out of the bx you cannot create a ticket with out a contact. But with that said in the LAN Client you can delete the contact and then the contact would not be resolved and the us the same problem would happen. So I will add the check in the ticket list  template.

**Comment by rjledger** [comment]
Thanks! - You are correct.. Under "normal" conditions there's a contact - BUT it is possible to remove contact and when that happens.. bang!.. no tickets list!

**Comment by jbest84** [comment]
Fixed via: https://github.com/Saleslogix/argos-saleslogix/commit/a78d7996713ebfab94bfcf1ef6b5ed0a3e614b92
