### ISSUE TITLE
sData Feed with Picklist Items?

### ISSUE THREAD

**Issue by rjsamp** [Saleslogix/argos-saleslogix#25]
As ADMIN:
SLX WEB Client, LAN Client look at Meeting Regarding Picklist in the Picklist manager or through Create Meeting Regarding\Description picklist selector, answer is 11 picklist items.

Log into SLX Mobile, create a meeting activity.....click on Regarding.....answer is 351 Picklist Items!!!

So it looks like sData is not filtering picklist items by 
1. All Admin created values
2. Only UserId logged in created values.

IE the sData payload is ALL picklist values for a given picklist regardless of creator.

SLX 7.5.4 HF 1-3 
SLX Mobile 1.1 (mobile running on iPad Safari)
SQL Server 2008 R2 64 bit.

**Comment by jhershauer** [comment]
Thanks for the details! A defect has been entered and this is scheduled to be fixed in the SData Provider for Sawgrass. It's not a mobile-specific issue.

Jeff

**Comment by rjsamp** [comment]
Glad to be of help Jeff. You were one of our favorite presenters at Boot Camp. Great Job! 

We were aware that this isn't SLXMobile specific (hence the title "sData Feed....."). We thought you were also Mr. sData so posted it here..... 

I've got a major customer (who discovered the bug in testing) rolling out SLXMobile shortly (Dec. 1).....anyway to get this fixed in 7.5.4 as well as Sawgrass? 

RJ Samp 

----- Original Message -----
