### ISSUE TITLE
New signature capture "control" - got any example/sample of usage?

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#26]
See that the sdk now has signature capture - any example/sample available?

**Comment by tremendo** [comment]
I'm working on a sample and some bugs, should post tomorrow (Wed)

**Comment by rjledger** [comment]
Great! You guys always come thru.
Looking forward to this capability and to try it on my DroidX (smartphone) as well as the Samsung Galaxy 10.1 tab.

rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjsamp** [comment]
Fantastic! Lot's of field sales and service teams that can use this functionality.

**Comment by tremendo** [comment]
Our Detail view doesn't exactly lend itself for easy display of the signature control. Need to come up with a better way, but for now I was able to torture it and show it in argos-sample, as a customization of the Lead. When logged in as Admin, look in Leads for Dumbledor, Albus, click to detail to see Signature in place of Notes, click to edit for playing with it.

**Comment by rjledger** [comment]
Neat!...
