### ISSUE TITLE
3.1 beta 2 - Add in customization module not working

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#274]
I have an add-in custom module we do on ALL systems. It works fine on 3.0.3 and 3.0.4 (gold).

It adds the "parent" to the Account Detail and Account Edit.

Normal technique of using 
      this.registerCustomization()
    to add the  lookup , etc

as well as 
      lang.extend('Mobile.SalesLogix.Views.Account.Detail, {..
   to extend teh query, add requestParentAccount function, etc..

What is NOT happening is I do not see the lookup control added to the detail nor the edit.

Fails in every browser as well as all mobility browsers..

This is going to break all our custom modules.. hope this is just a "bug" that is because it is beta2... otherwise, 3.1 is something we cannot use.

**Comment by rjledger** [comment]
OK.. here's the problem:
  There was a change made to the (template) index.aspx (and teh others) that removed the enumeration on the configuration folder - end result - no custome modules (including teh sample) work. I added it back in and my test custom module worked instantly.

Here's what was:

```
<script type="text/javascript">
(function() {
    var application = 'Mobile/SalesLogix/Application',
        configuration = [
            'configuration/production'
        ];
```

Here's what it looks like now in my test/dev/demo:

  <script type="text/javascript">
    (function() {
        var application = 'Mobile/SalesLogix/Application',
            configuration = <%= Serialize(
                Enumerate("configuration", (file) => file.Name == "production.js")
                    .Select(item => item.Path.Substring(0, item.Path.Length - 3))
            ) %>;  

..

**Comment by jbest84** [comment]
Good catch, I will add that back in for the *aspx pages.

**Comment by rjledger** [comment]
Good! - thanks!
