### ISSUE TITLE
3.1 beta 2 - click on help (default english.. ) throws error

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#276]
Console/errors shows error:
      GET http://localhost:3344/slxmobile/help/help_en.html

**Comment by jbest84** [comment]
Not a 3.1 issue. This probably goes back to 2.0. The help file will try to load a localized version of the help by looking at the current Mobile.CultureInfo.name property. It falls back to "help.html". We can either rename help.html to help_en.html or add an exception to the code that loads it.

**Comment by rjledger** [comment]
Yep.. know that ;-)

It would be nice to have something in place so that when things are “normal” we don’t see an error “tossed”..
Any issue changing it to help_en?

rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
FAX: +1 603.369.6454

**Comment by jbest84** [comment]
This was [fixed](https://github.com/Saleslogix/argos-saleslogix/tree/develop/help/locales/crm/en) in  3.4. Help now lives in a locales folder with subfolders (en, de, etc). Fallback is still EN.
