### ISSUE TITLE
dojo version - latest - how to add more than one hash tag query at a time

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#28]
The sample only shows how to do one HT at a time. w/Ext based mobile, we could do multiples. 

Any easy way to do this w/the dojo?

Ext based:
            hashTagQueries: Ext.apply(Mobile.SalesLogix.Account.List.prototype.hashTagQueries || {},{
                'cust': 'Type eq "Customer"',
                'lead': 'Type eq "Lead"',
                'vend': 'Type eq "Vendor"',
        'slxbp': 'SubType eq "SLX BP"',
                'my': function(){
                    return String.format('AccountManager.Id eq "{0}"',App.context['user']['$key']);
                }
            })

dojo:
??
One->
this.registerCustomization('list/hashTagQueries', 'account_list', {
            at: true,
            type: 'insert',
            value: {
                    tag: 'my',
                    query: function() {
                        return dojo.string.substitute('AccountManager.Id eq "${0}"', [App.context['user']['$key']]);
                    }
            }
        });

Many????

**Comment by rjledger** [comment]
Got my answer on the Community - Thanks Tony!

**Comment by wskidmore** [comment]
We could keep it open until support is added.

To summarize from Community:

registerCustomization does not have support for `insert`-ing multiple "row" objects in a single call. Once this capability is added to the customization handler then we can update argos-sample to show usage of adding multiple hash tags in a single pass.

**Comment by rjledger** [comment]
Sure!...

**Comment by rjledger** [comment]
registerCustomization supports multiple hash tag inserts in one call as of 2.0. Example is in argos-sample:
this.registerCustomization('list/hashTagQueries', 'opportunity_list', {
                at: true, // insert anywhere (hash tag queries are not ordered)
                type: 'insert',
                value: [
                    {
                        tag: 'l500k',
                        query: 'SalesPotential lt "500000"'
                    },{
                        tag: 'g1m',
                        query: 'SalesPotential gt "1000000"'
                    }]
            });

**Comment by jbest84** [comment]
Thanks RJ.

**Comment by rjledger** [comment]
You are welcome. I’ll look thru the rest of the issues (I’ve submitted) to see if we might close more out.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)
