### ISSUE TITLE
3.0.x and 3.1 - Full path problem in a custom module

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#287]
I have some modules (ex:argos-procedure) where I need to use:
    //'../_MetricListMixin',
    //'../_RightDrawerListMixin',
    //'../_CardLayoutListMixin'

The problem is there is no "full path ref" to these items and have tried a couple of approaches to solve it. The argos-sample does not use these in it's "define" so there's no working example.

**Comment by jbest84** [comment]
The full path would be 'Mobile/SalesLogix/Views/_MetricListMixin'

**Comment by rjledger** [comment]
Thanks - I don't know how I missed that.. must have had a "brain stall" ;-)
