### ISSUE TITLE
3.2 Beta 2 - uploads attachments but not displaying PDF's - get "blank" view

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#289]
Using FF on the desktop:
    3.0.4 - pdf uploads to attachments and displays fine
    3.1 B2 - pdf uploads to attachments and blank display

no errors in (mobility) error lofs

FYI - latest FF 32.0.3

**Comment by CHenrie** [comment]
I can not reproduce this In FF or Chrome on the desktop.

**Comment by rjledger** [comment]
Are you using the “3.1 B2” – or your latest? I was using the “released” VFS image and deployed via AA.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by CHenrie** [comment]
I have the latest but I have tested but really nothing has changed. What size of pdf file are you uploading

**Comment by rjledger** [comment]
Chased it down to a "caching issue"  UGH!
