### ISSUE TITLE
3.2 Beta 2+ Icons??

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#291]
Background:
  I have updated my 3.2 B2 to have all the changes that are in the "development" path

Couple of icon issues:
 A - I do see there are no "icons" displayed on the "home list" - not a (big)problem - but I expect when upgrading customers some will ask for me to put them back.
 B - Quick (contact) Actions - I see the word ICON displayed - and my icons are in teh correct path but do not get displayed - I do know that will be an issue w/customers.

Custom Icons do display just fine - but how do we restore displaying the original OOTB icons?

**Comment by rjledger** [comment]
I  Closed the above - should not have..

**Comment by jbest84** [comment]
No plans to restore old icons. UI was overhauled in 4.0 to use the Infor Design System controls (Soho), which are SVG based.

https://design.infor.com/
