### ISSUE TITLE
Reseller on Opp Detail

### ISSUE THREAD

**Issue by sturev-zz** [Saleslogix/argos-saleslogix#293]
It appears everything is wired up but it shows as an empty row...  found this issue by trying to add it to the list view and it shows null also, no errors...

**Comment by rjledger** [comment]
A - are you changing the actual OOTB code or trying to make a custom add-on module?
B - did you check SData to make sure it is "included"?
C - did you add it to the query in all views?

**Comment by sturev-zz** [comment]
disregard, it was a cache/iis issue...  fyi, the ootb detail view has the reseller...  I was doing a custom override to the list view to add it and it wasn't showing on either location so I thought something was wrong with the base...

**Comment by rjledger** [comment]
I am finding 90%+ of the issues that happen seem to be related to cache/IIS – big PITA and time waste!

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
