### ISSUE TITLE
3.2 B2+ - If the attachment is a zip file - we get a server error

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#294]
Went into myAttachments and clicked on a zip file - this was on Windows7 desktop using FF

Looking at the error log:
    date
           09/30/2014 10:46 AM
    error
           failure

More Details
    error
           {}

**Comment by jbest84** [comment]
Can you go on the server's event log and send us that information please?

**Comment by CHenrie** [comment]
Also what SLX service pack are you on

**Comment by rjledger** [comment]
Version 8.1 - Has all the latest.. including the “3b’s.

FF response error in Firebug:
{
  "$updated": "\/Date(1410313059000)\/",
  "$key": "e6UJ9A00009L",
  "$url": "http://cp.rjlsystems.net:81/sdata/slx/system/-/attachments('e6UJ9A00009L')?_includeContent=false&select=description,user,attachDate,fileSize,fileName,url,fileExists,remoteStatus,dataType&include=$descriptors&_includeFile=false&_t=1412101436912",
  "$lookup": "http://cp.rjlsystems.net:81/sdata/slx/system/-/attachments?_includeContent=false&select=description,user,attachDate,fileSize,fileName,url,fileExists,remoteStatus,dataType&include=$descriptors&_includeFile=false&format=json&_t=1412101436912",
  "$httpStatus": 500,
  "$etag": "Lqlu+OeF20c=",
  "$diagnoses": [
    {
      "severity": "Error",
      "sdataCode": "ApplicationDiagnosis",
      "applicationCode": "source=SDataExceptionDiagnoses; exceptionKind=BaseException; exceptionSource=mscorlib; exceptionType=System.IO.DirectoryNotFoundException; slxErrorId=SLXB3530709FFD74692",
      "message": "We're sorry, you've encountered an error. If applicable, please try again.",
      "stackTrace": "",
      "payloadPath": ""
    }
  ],
  "$descriptor": "20140909",
  "$schema": "http://cp.rjlsystems.net:81/sdata/slx/system/-/attachments/$schema?_includeContent=false&select=description,user,attachDate,fileSize,fileName,url,fileExists,remoteStatus,dataType&include=$descriptors&_includeFile=false&format=json&_t=1412101436912",
  "$template": "http://cp.rjlsystems.net:81/sdata/slx/system/-/attachments/$template?_includeContent=false&select=description,user,attachDate,fileSize,fileName,url,fileExists,remoteStatus,dataType&include=$descriptors&_includeFile=false&format=json&_t=1412101436912",
  "$post": "http://cp.rjlsystems.net:81/sdata/slx/system/-/attachments?_includeContent=false&select=description,user,attachDate,fileSize,fileName,url,fileExists,remoteStatus,dataType&include=$descriptors&_includeFile=false&format=json&_t=1412101436912",
  "$service": "http://cp.rjlsystems.net:81/sdata/slx/system/-/attachments/$service?_includeContent=false&select=description,user,attachDate,fileSize,fileName,url,fileExists,remoteStatus,dataType&include=$descriptors&_includeFile=false&format=json&_t=1412101436912",
  "attachDate": "\/Date(1410313058000)\/",
  "dataType": "R",
  "description": "20140909",
  "url": null,
  "fileName": "20140909.zip",
  "fileExists": false,
  "fileSize": null,
  "remoteStatus": null,
  "user": null

The Windows error log had a dozen or so errors but were pointing to “Modified” being missing…. What “modified”?.. don’t see it in the query.. tried SlxProfiler as well and nothing there.

..

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
Cannot reproduce on the latest development mobile, using Windows 10 and Firefox 77.0.1. When I click an attachment that is a zip, I get a download prompt.
