### ISSUE TITLE
3.1 Gold release -  View Address on Contact/Account

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#295]
It appears to not be working on the desktop w/FF. Deployed 3.1 Gold to two different SLX db's - one my production, the other an 8.1 demo/eval db - FF on two different systems.

Update:
   Works if the browser is IE.. does not work w/FF or Chrome.  :-(

**Comment by CHenrie** [comment]
I can not reproduce this with chrome. do you have some steps

**Comment by CHenrie** [comment]
Do you have any popup blockers enabled

**Comment by rjledger** [comment]
Nope. no blockers. Just tried my droid tablet (w/ff) and had the same result (or lack of).. Just does not make sense. The code is the same as was in 3.0.3

**Comment by CHenrie** [comment]
Are there customizations?

**Comment by rjledger** [comment]
Nope.. all custom module disabled.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by CHenrie** [comment]
Do yp have a url we can hit

**Comment by rjledger** [comment]
Yep.. but prefer to send the url info to you.. and not let it get posted to Github…

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by CHenrie** [comment]
whats your email address

**Comment by CHenrie** [comment]
Yes, this is what I found:

Chrome, Safari and IE is works form both the quick action on contact and in the account on the address field.

For FF it only works on the account address field. 

I have QA creating a defect for this even though we don’t officially support FF for mobile. 

Thank
Cam

**Comment by rjledger** [comment]
Cam, Thanks!
   On browser support – Dave Wallace has said several times the goal of SLX is to be “browser agnostic”.

Until 3.1 – I’ve not experienced problems w/mobility w/FF. The published compatibility guide says FF is supported.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
