### ISSUE TITLE
3.2 Gold release (VFS copy) - seeing an error about fontawesome

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#296]
Deployed to both test/dev (8.1) as well as out production 8.1
Firebug says:

"NetworkError: 404 Not Found - http://cp.rjlsystems.net:81/informobile/content/css/themes/fonts/fontawesome-webfont.woff?v=4.1.0"

file there is:
fontawesome-webfont.woff

**Comment by jbest84** [comment]
You can add the mime type for woff in your web.config:

`<mimeMap fileExtension=".woff" mimeType="application/font-woff" />`

Otherwise you can ignore the error, font awesome will fall back to a ttf font.

**Comment by rjledger** [comment]
So it is a bug then – right?

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
Not really. It falls back to the ttf font. The error message is just a 404. The application is not impacted in any way. If font awesome broke you would see a bunch of squares for all the icons.

**Comment by rjledger** [comment]
I can see that it is working (on ttf font) – so I see a couple of solutions here:
       Dealing w/the mime issue in the config file (which I’d expect should have been handled automatically but is not)
       Deleting the file fontawesome-webfont.woff in argos-sdk/libraries/font-awesome-4.1.0 (will it get rid of the error?)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by rjledger** [comment]
Made same change to .config in my 3.2 source as you did
