### ISSUE TITLE
3.1 Gold release - issue w/duration in edit.js on creating/editing an activity - broken.

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#298]
In 2.x and 3.0.x if one keyed in "3 min" it would automatically make it 30 minute(s) on exit of control. in 3.2 it changes it to 3 hour(s). The problem spills over to the alarm  as well. Keying in 5 hou gives 5 minute(s).

It appears it only recognizes the key'd in values ONLY if you have pre-selected via the picklist and just change the number - a bit clumsy and makes it harder to set the duration you really want to set (ex: 1.5 days) Please restore functionality.

**Comment by jbest84** [comment]
I changed the title of this to 3.1, since there is no 3.2 (yet).

**Comment by rjledger** [comment]
My mess-up ..

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
