### ISSUE TITLE
3.1 Gold Release - Related Items counts not updating

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#299]
If one uses a Quick action (on an Account/Contact) to Schedule an activity, create note, etc the Related  Items counts are not updated to reflect the additional Activity, History, etc.

I suspect this is how it is (not) working throughout all entities.

**Comment by rjledger** [comment]
Status?

**Comment by klbratton** [comment]
This issue has been logged.

**Comment by rjledger** [comment]
Will it get fixed in the next update?

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
INFORCRM-3049
