### ISSUE TITLE
In Calendar on Weekly View - clicked on today - Still Weekly

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#3]
If the last thing you clicked on was weekly - then if you click on the Today btn - it will show a weekly view for "this" week

**Comment by wskidmore** [comment]
This is by design, however, in Month View clicking 'Today' goes to Day View for 'today's' date. I will bring it up in the next meeting to see if there can be better consistency between the different views. Thank you for the feedback!

**Comment by rjledger** [comment]
OK... 
It just seemed a bit "weird".. But looking at the way "Today" btn functions in the Slx Windows/LAN client - it is really correct.

Suggest a note somewhere that explains this is consistent.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
Yes, that is true. Would you rather it go to a different week?  :-)

**Comment by rjledger** [comment]
Actually.. looking closely it seems to work a lot like the "today" button does in the SalesLogix (Windows/LAN) Calendar. It's probably correct. I noticed if I was looking at "next week" and clicked on Today - it went to THIS week - and that is just fine.

It's just that at first it seemed a bit strange and probably needs a small explanation as to what the "Today" button really does.

I'd leave it as is.

Thanks!

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
