### ISSUE TITLE
Hash Tag Search Queries

### ISSUE THREAD

**Issue by rjsamp** [Saleslogix/argos-saleslogix#30]
I like this capability....although this should be USER Friendly, not programmer friendly (or should be both).
I'm liking this:
# !(AccountName like ‘Abbott%’)

Another
# !(Type like ‘%Cust%’)

This too:
# !(AccountName like ‘Abbott%’ and Type like ‘%cust%’)

However the queries need to be  LOCALIZED Display name based (User Friendly), not simply Property Based (Programmer Friendly) (I'm assuming you want # queries to be used by User's correct? or is that not their purpose?)

So 
# !(AccountNameDisplayName like 'Abbott%')

Another
# !(TypeDisplayName like '%Cust%')

This too:
# !(AccountNameDisplayName like 'Abbott%' and TypeDisplayName like '%cust%')

And maybe the spaced display names need to be in " " or [ ] to handle spaces in Display Names.

This should NOT be in Programmer Property stuff only....

ALSO is this going to be a SQL Injection Security breach? Anytime I  see non-parameterized SQL Server Queries you scare the heck out of me.....

**Comment by jhershauer** [comment]
Hi RJ. You're confusing #! with #. 

The # symbol (or Hashtag search) is a way of providing "simple"  querying capability to the user. You can wrap up any kind of  query expression you want in a single word, like #closed, #mine, #meeting, etc.

#! is an entirely different animal, and can be thought of as almost an Easter Egg, allowing SData Query aficionados to override the out-of-the-box search functionality with an SData query filter.

Stepping back a little, the basic search feature is about as simple as you can get. You just enter text or partial text that you want to find.

So...as you can see, we're very much catering to the non-programmer with our search feature, yet allowing an "override" of the basic search for entering SData queries (not SQL queries).

I'm going to look past all of the aggressive "should NOT" type of wording in your comment, related to the override feature, and take away that you would like to be able to provide the average user some kind of more advanced querying capability.

Perhaps you're right that, if we could pull in the "Display Names", they could be combined with the basic SData syntax to provide a reasonably friendly query language. We'll put it on the idea board. We're also looking at more visual ways of facilitating filtering, which would arguably be more friendly.

Thanks,
Jeff

**Comment by jhershauer** [comment]
Ha! Just got caught by the github markdown support above when I attempted to start a paragraph out with the # character.

# problem corrected. :-)
