### ISSUE TITLE
index.aspx - fallback-bug

### ISSUE THREAD

**Issue by ghost** [Saleslogix/argos-saleslogix#300]
localization = <%= Serialize(
EnumerateLocalizations("localization")
.Select(item => item.Path.Substring(0, item.Path.Length - 3))
) %>;
require.on('error', function(error) {
console.log('Error loading localization, falling back to "en"');
bootstrap(fallBackLocalization);
});
if (localization.length === 0) {
fallBackLocalization = <%= Serialize(
EnumerateLocalizations(string.Empty, "localization", "en")
.Select(item => item.Path.Substring(0, item.Path.Length - 3))
) %>;
bootstrap(fallBackLocalization);
} else {
bootstrap(localization);
}

should be:

localization = <%= Serialize(
EnumerateLocalizations("localization")
.Select(item => item.Path.Substring(0, item.Path.Length - 3))
) %>;

fallBackLocalization = <%= Serialize(
EnumerateLocalizations(string.Empty, "localization", "en")
.Select(item => item.Path.Substring(0, item.Path.Length - 3))
) %>;

require.on('error', function(error) {
console.log('Error loading localization, falling back to "en"');
bootstrap(fallBackLocalization);
});
if (localization.length === 0) {
bootstrap(fallBackLocalization);
} else {
bootstrap(localization);
}

**Comment by jbest84** [comment]
Thank you for the report @ViktorLoerincz
