### ISSUE TITLE
SalesLogix Mobile 2.1 not work in Chrome

### ISSUE THREAD

**Issue by Iveth** [Saleslogix/argos-saleslogix#303]
Hi, I have a big problem, my SalesLogix Mobile 2.1 for 7.4, not work in Chrome, It works perfect in Firefox, with its custumizations, but in Chrome, It presents one error when It charge the file base.css.

Failed to load resource: net::ERR_CACHE_MISS

Can you help me please?.

Regards.

**Comment by jbest84** [comment]
You need to add a configuration to the index*.html files and turn the ReUI FX off. Here is a commit that fixes the issue: https://github.com/Saleslogix/argos-saleslogix/commit/102072f9aa619e8ae4f552d28d4851d73e3fb9e5#diff-35fe369dda0a22709af6298344742602

**Comment by Iveth** [comment]
Thanks, I applied the changes and the application is running ok in Chrome.

Regards.
