### ISSUE TITLE
vers 3.1.1 - Issue with creating an Activity with PHONE number

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#307]
Scenario:
   If you pick a contact the WORKPHONE loads as default just fine.
   However, if you override the number and "save" it reverts back to the default.
   If I bring up the EDIT after it is saved, it is possible to override the number - a bit "messy" especially on a smartphone..

We need to:
    a - have the override stick

Optional (Really Nice ;-):
   allow "picking" ANY of the numbers from the contact - ex: Workphone, Mobile, etc.

**Comment by klbratton** [comment]
Thanks RJ ... I have logged this issue.

Kathy

**Comment by rjledger** [comment]
Thanks!

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
Business rule issue in activities. Logged internally to INFORCRM-3109
