### ISSUE TITLE
Edit view for Activity - 7.5.4 fall back still displays "Location" field

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#32]
Subject says all... Activity.Location does not exist in 7.5.4. UNLESS you guys plan on adding it?

Detail View also displaying field.. seeing [object Object] as a value as well.

What is the plan for location?.. an address?.. as a text field by itself, it's basically not useful at all.

**Comment by wskidmore** [comment]
This might be a server detection issue as Location is added via:

```
if(App.serverVersion.major >= 8)
{
    // dojo extends for location support
}
```

EDIT: This is a server detection issue. If you hardset (saleslogix/src/Application.js) the server version to 7 location is no longer there.

**Comment by rjledger** [comment]
I'm running on 7.5.4 and I have an "alert" msgbox that pops up telling me it is on 7.5.4 and not 8.. still get the location "error". Looks like a bug to me

**Comment by rjledger** [comment]
In the current master Application.js I do not see the line of code you are talking about...

It's testing by using: 
   if (this.context['securedActions'])
      v8....
   else
      7.5.4

**Comment by rjledger** [comment]
AH.. see it now in ApplicationModule.js...
  No "else" part to the "if" to properly set things up for App.serverVersion.major < 8
;-)

Also.. as just a text field.. location is (almost) useless.. needs to be linked to a real address record in the Address entity/table.

**Comment by wskidmore** [comment]
To hardset the server, its near the top:
https://github.com/SageSalesLogix/argos-saleslogix/blob/master/src/Application.js#L31

The `if >8` shouldn't have an else as it should ONLY add Location if its >8 - otherwise don't add anything.

In `ApplicationModule.js` if you add this:

```
alert(App.serverVersion.major);
if(App.serverVersion.major >= 8)
{
    // Activity Location Sawgrass+
...

```

It should alert `7`. If it does alert `7`, then something very odd is going on. If it is alerting `8` then it's the server detection.

**Comment by rjledger** [comment]
Something "odd" is happening.
I have a js alert popup in the else code in Application.js where it tests for 8... and I always get the "7 side. BUT in ApplicationModule we seem to fall down the "8"...

AH-Ha... added an alert to the AM.js and found that thee ApplicationModule code is running before the Application code.

So the detection is in the incorrect place.. it should be in ApplicationModule.. not Application!
rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by wskidmore** [comment]
That is indeed it! Going to have to rethink that whole flow - as one should be able to target a version with a custom module.

**Comment by rjledger** [comment]
Glad we caught it at this stage... could have been a lot more messy later on ;-)

BTW... You can get the actual Saleslogix Version from the "SYSTEMINFO" table. Specifically the DBVERSION field. 
Typically it will say:
    7.54 (Saleslogix 7.5.4) .. or 7.5 (for 7.5.0).. Don't have an 8 so I'd guess it is 8.0

This is what we have used (for almost) forever as a "flag" on version info

a...and yep.. I'd like to be able to use the server version info to enable/disable a custom module...

When you have something, let me know and I'll give it the hard-tire "kick" ;-)

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Any update on changes to the version detection logic to make it actually work  right?

I see there has been a "fork" of code to make it compatible w/7.5.3 w/HF4 - I would have thought maintaining a single source w/version detect/fallback  would have been the approach rather than ending up w/multiple versions of the source code for different versions of SalesLogix .

**Comment by rjledger** [comment]
Latest dojo source (as of 3/4/2012) - "fallback" is still not detecting 7.5.4 correctly and the "locale" fields show up in Activity....

I hope this will be fixed soon since I am building some custom mods that need to be able to test for the SlxVersion.

**Comment by rjledger** [comment]
Current 20_for_754 appears to correct for this by simply replacing teh entire Activity Edit.js w/it's own 754 friendly module.
