### ISSUE TITLE
vers 3.2.x - problem w/"Lookup control" at top

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#323]
The "x" and the Lookup "button" are NOT displaying on an Android device using the default chrome browser(I am on "Kitkat") - I just realized this when I went and used the testiphone.com (iPhone simulator) and it appeared.

**Comment by jbest84** [comment]
The clear "X" on input fields is vendor specific. We removed our clear image and lookup button in 3.2. You can simply click enter on the keyboard to invoke the search. We highly the text when you focus the lookup so you can simply hit backspace on the keyboard instead of clicking the clear button.

**Comment by rjledger** [comment]
Is there an easy way I can add it back for my (customer) droid users? They are complaining.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
It is an option in the search widget: https://github.com/Saleslogix/argos-sdk/blob/develop/src/SearchWidget.js#L76

**Comment by rjledger** [comment]
Thanks!

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by rjledger** [comment]
IMHO - I don't agree w/closing this issue - yet.
I did find an issue w/enabling the "look-and-feel" for 'droid users - it really does not behave well with all the "newer" Infor changes and gets rather "ugly" - 

What we really need is to have it look/behave the same inall browser/devices - not just Apple/ios stuff - customers just don't like it happening that way. After all, most are  in teh BYOD world and have droids and apple toys.

Can't we just get it back to the way it was before across the board instead of the way it is now?
