### ISSUE TITLE
v3.2.1 - Clicking on Today - broken refresh

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#326]
Scenario:
    A - On the Calendar and Month (view) is selected
    B - Local TZ is EDT
    C - The date is the 9th of Feb and it is "today".
    D - Midnight happens and it is now "tomorrow"
    E - Clicking on the "Today" icon results in:
               1 - the 9th appearing in dark green
                2 - the 10th in light green

Basically - it still "thinks" it is the 9th when it is really the 10th!

If I click on the Week (view button) and back on the Month (view button) it will show the 9th no longer selected and the 10th (selected) in light green.

IMHO - combine this with bug #320 and we see an overall problem w/mobility showing us the in-correct date.

**Comment by jbest84** [comment]
Fixed in the referenced changeset. Closes MBL-10848
