### ISSUE TITLE
Carriage Returns on History LongNotes

### ISSUE THREAD

**Issue by johnwfoster** [Saleslogix/argos-saleslogix#334]
Using the standard Add Note link on a Contact detail.  If you type Notes with carriage returns, they do not display properly in the Windows Client Notes/History tab or Edit/View History.  They do appear properly if you edit or view the History in Web or Mobile.

**Comment by rjledger** [comment]
Yep - The only way you can see them properly is to do an "edit". IMHO it would be nice to see Edit and Detail use the same layout for memo/text. Wonder if one could hack in something ;-)

**Comment by jbest84** [comment]
LAN issue.

**Comment by rjledger** [comment]
How is this a LAN issue?
It seems itis a memo/text control issue in the mobility app - this is what he (and I) are talking about.

**Comment by jbest84** [comment]
The issue states they appear fine in Web/Mobile. That would imply the LAN client needs to render notes added from web/mobile properly.

**Comment by rjledger** [comment]
Actually - In the mobile Web app - when looking at the "detail view" of Notes/History  - the text "runs on and on" w/no "formatting. If you click Edit - you see it "properly".

So if a user is not allowed toedit - they see it in a bit of a messy form - no "format".

FYI - just validated it in 3.4.2
