### ISSUE TITLE
Your change to round up the Activity Create date/time...

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#336]
Just found a bug in it....
When you go to the calendar and pick a day.. say April 20th 2015 and create an activity - the default Date is TODAY - not April 20th. The time is OK.. just the date is messed up.

**Comment by jbest84** [comment]
We cannot reproduce this. Are you sure your code is up to date? Did you take this changeset: https://github.com/Saleslogix/argos-saleslogix/commit/6522317b6f9808f452d69f0473ba75f8e714b5e5 which was done prior to the time change?

**Comment by rjledger** [comment]
ARGH…. I missed that change… Got it all in now (in my 3.2.1)..

Suggestion – expand the “version stuff” so that we can easily identify a customized mobility.
If I did it… is this all I need to touch?:
     Src\Applicaion.js
             mobileVersion: {
                    ‘major’: 3,
                    ‘minor’: 2,
                    ‘revision’ 1,
                    ‘custom ‘ : 0
            }

```
        versionInfoText: ‘Mobile v${0}.${1}.${3}.${4}’

        getVersionInfo function() {
          var info = string.substitute(this.verionInfoText,
               [
                   this.mobileVersion.major,
                   this.mobileVersion.minor,
                   this.mobileVersion.revision,
                   this.mobileVersion.custom,
                   this.serverVersion.major,
               ]);
        return info;
        }
```

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
