### ISSUE TITLE
v3.2.1 and v3.3 - After updating Infor CRM to SNC06 and Core 06 - having issues

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#347]
I am experiencing ""A Server error occurred while requesting data" dialog error popup with picklists.

Entry in Error logs on the mobile not happening.

Happens w/all browsers and my droid as well.

Any ideas?

**Comment by jbest84** [comment]
Our 8.1 QA instance is 06 as well. What is the error in the event log on the SData server? This sounds like a platform issue, not a mobile issue.

**Comment by rjledger** [comment]
OK... tracked it down to missing properties in PickList entity:  LANGUAGECODE and FILTER. .. and yes I had applied the bundle but somehow it was not brought over.... ;-(

FYI - in the AA it refers to PickList SData:
     Hostname:port/sdata/slx/dynamic/-/picklists ....

It should be:
     Hostname:port/sdata/slx/system/-/picklists ...

## 

RJLedger - www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
