### ISSUE TITLE
Quickaction Add Account / Contact does not adhere to user role security

### ISSUE THREAD

**Issue by ArjenR** [Saleslogix/argos-saleslogix#351]
Hi. 

We found that a user without any role assigned or only read allowed to account and contact, is still able to add an account / contact via the quick action.

Kind regards, 
Arjen

**Comment by jbest84** [comment]
Resolved by 992c1b3171f88b7e41c00f3c99f683e43416b9e4 and b4dba20102ee9b347e864b03b3c981a8cd855a9b
