### ISSUE TITLE
Adding Activities - Edit.js

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#357]
Somewhere something changed:
 At one time you could pick the Contact and it would auto-fill the Account. This created a nice, quick on-click scenario.
Now it's not allowing me to pick a contact (acts locked out/disabled) unless I pick an Account first! This creates extra work as 99% of the time it's the Contact we want and really don't care about teh account!

Any idea as to what happened and how can I "fix it"?

**Comment by jbest84** [comment]
Do you know what version it broke?

**Comment by rjledger** [comment]
Not 100% sure.. I think it it worked in 3.2.1 .. but not sure

**Comment by rjledger** [comment]
Just checked a 3.2.0 - it works there.

**Comment by jbest84** [comment]
@rjledger It looks like [this](https://github.com/Saleslogix/argos-saleslogix/commit/d30f5708b26ed39d7bd31dfa6e4c5b3bbadfbfb5) commit in 3.3.x broke this.

I have a fix for the original phone number issue, and this one. I will push it up shortly.

**Comment by jbest84** [comment]
@rjledger Can you verify if this fix works for you? https://github.com/Saleslogix/argos-saleslogix/commit/d5147c77258a9edcd09d5b0be472764af3318682

Disclaimer: QA has not yet validated this, the testing was done on my dev machine.

**Comment by rjledger** [comment]
Works! Thanks!
