### ISSUE TITLE
3.3.0/1 - problem with using view.js

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#361]
I've got a custom module using Google Maps. I've added the capability to display a map that shows a route from where one is (geolocation) to the primary address of an Account/Contact/Lead.

This works fine in 3.2.x but now (no matter what browser I use (Edge, IE11, Chrome, FF) on any device(pc/droid smartphone, etc) it will not "display" the map and complains about the "view".

In my ApplictionModule.js I reference:
     'Sage/Platform/Mobile/View'
I did notice you changed it to: 'argos/View'

I tried both ways and they still fail.

**Comment by jbest84** [comment]
Here is what changed in View between 3.2 and 3.3: https://github.com/Saleslogix/argos-sdk/compare/3.2.x...3.3.x#diff-ce4229b24108600735f6e9fe9281461c

It is mostly formatting changes, and an addition to an error handler layout creation. You are still free to use Sage/Platform/Mobile/View, we export that namespace for backwards compatibility: https://github.com/Saleslogix/argos-sdk/compare/3.2.x...3.3.x#diff-ce4229b24108600735f6e9fe9281461c You will need to create a map to it though: https://github.com/Saleslogix/argos-saleslogix/blob/develop/index-dev.html#L130

**Comment by rjledger** [comment]
Thanks for the info. OK now.
