### ISSUE TITLE
v3.3.x - GroupedList not working as before

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#369]
I have an entity (Assets - AccountProduct) setup in a GroupedList for a customer.

In 3.3x if the view space is full it will vertically scroll thus it is impossible to view the entire (grouped) list3.3.x. - What changed?

FYI - Just found this - it it the answer/fix?
http://www.mediacollege.com/internet/css/scroll-always.html

**Comment by jbest84** [comment]
The grouped list overrides the widget template of the list. We added a scroller node a while back, and never added it to the grouped list. The referenced commit above should resolve it.

**Comment by rjledger** [comment]
AH!
I knew it overrode it but was not sure where to do the fix. Thanks!
rjl

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jbest84** [comment]
No problem.

**Comment by rjledger** [comment]
How do I get my hands on:
 min/css/themes/crm/sdk.min.crm.css

**Comment by jbest84** [comment]
You can click the "Raw" on the file. https://raw.githubusercontent.com/Saleslogix/argos-sdk/bff97a5fbe508efbd723304ae13100838a00158a/min/css/themes/crm/sdk.min.crm.debug.css
