### ISSUE TITLE
Latest Change in Contact.list results in Account Name not listed..

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#37]
Was running a test on the latest dojo code and found AccountName not in the list w/teh Contact Name.

Before:
  QuerySelect was obtaining the AccountName from the Contact record
Now:
  QuerySelect obtaining the Accountname from the related Account

ItemTemplate was not changed:
 IS:
itemTemplate: new Simplate([
            '<h3>{%: $.NameLF %}</h3>',
            '<h4>{%: $.AccountName %}</h4>'

Should be:
itemTemplate: new Simplate([
            '<h3>{%: $.NameLF %}</h3>',
            '<h4>{%: $.Account.AccountName %}</h4>'

Question.. why was the querySelect changed?  Sometimes it is valid for the Contact to have a different AccountName than the Account has. This change makes that no longer possible.

**Comment by tremendo** [comment]
My bad, sorry about that, I just added AccountName back in.

**Comment by rjledger** [comment]
NO Problem!... just glad I caught it... and that you fixed it. ;-)

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Thanks! - I assume the Account.AccountName has to do w/the fix in Activity so that one can select the Contact first and then get the Account data filled automatically.

**Comment by tremendo** [comment]
Exactly. Now you can select Contact, or Ticket, or Opportunity first before Account, the Account gets automatically filled then the dependency restored in the other fields that are also related to Account.

**Comment by rjledger** [comment]
Carlos,
Neat "trick"....
 Great productivity (and fewer "clicks") change! I've the latest 2.0 up on out 7.5.4 production system and using it daily.
rjl

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
