### ISSUE TITLE
Remote (LAN and Web - Individual and Office) users - Rollover issue (lack of)

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#38]
Scenario (taken directly from my own daily experience):
   User is on a "synching" SalesLogix remote
   User sets up several activities timeless w/rollover enabled (ex: a list of to-do's)
   Next day, user accesses SalesLogix Activities via their Mobile device (droid) - list of to-do's are still scheduled for yesterday.

The only way one can get the activities to "rollover" is to log into the remote and synch it. - We need a way to get previous timeless/rollover Activities to roll..

**Comment by rjledger** [comment]
Any chance we will see this issue fixed soon?

**Comment by jperona** [comment]
RJ,
In Sawgrass (SalesLogix 8.0) Timeless Activities are rolled over by a Scheduled Job nightly by the new Job Server component.  The client is no longer responsible.

**Comment by rjledger** [comment]
John,
 GREAT! I had been "cheating" by running a nightly job via Windows Task Scheduler that did a provider connection.
Definitely something that needed to be done "server side"...

Keep up the good work!

rjl

## 

RJLedger – www.rjlsystems.net
Blog: www.rjlsystems.net/blog
Direct Phone: +1  508.809.9513

-----Original Message-----

**Comment by rjledger** [comment]
Doesn't fix the problem for 754 and 1.2
