### ISSUE TITLE
Note-History Security issue in 1.2 and 2.0 

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#39]
User can see notes that belong to Accounts/Contacts/Leads/Tickets, etc that they should not see.. This is not a problem at the entity level since it "filters" it out due to the relationship.  It is a "home page GoTo History" issue.

**Comment by sturev-zz** [comment]
Is this still an issue?

**Comment by rjledger** [comment]
With ANY version of Mobility on 754 - yes.

This is such a severe security hole that all my customers have me remove it (Go To Notes-History) from the Home Page.

**Comment by sturev-zz** [comment]
Thanks RJ...  is this considered a mobile or a provider issue?  Is any ver of SLX/Mobile 'fixed'?

Did you ever get this http://community.sagesaleslogix.com/t5/Mobile-Developer-Discussions/quot-Notes-History-quot-security-bug/m-p/140375#M676 to work?  If so, is it a solution or is it a hack?

**Comment by rjledger** [comment]
This is a problem because the HISTORY table/entity does NOT have a SECCODEID field – never has… so there is no way for the OOTB provider (pre 8.0) to handle the problem. You will have to implement a “custom” provider Security extension (dll) to do it.

In 8.0 there’s been a bit of a “re-write” in the various provider extensions to de-couple the History Security from Activity Security. This is great for those who upgrade to 8.0 …. BUT it leaves 100% of the “pre-8.0” installs with a major security issue.

What’s needed is for SalesLogix to release a HotFix to 7.5.4 to fix the security hole.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by sturev-zz** [comment]
Agreed...  thanks RJ.

**Comment by jperona** [comment]
7.5.4 - Contains a Provider Extension in the SDK Examples>ProviderExctensions>HistorySecurity that is the precursor to the one used in 8.0 OOTB.  You can install that one if you like

**Comment by sturev-zz** [comment]
RJ do you have a cheat sheet on steps to remove the History link from the home page?  (I don't really want to wire up an override if I don't have to...)

**Comment by rjledger** [comment]
You really only have a couple (or three ;-) of choices:
    A – Implement the Provider (custom) extension shipped w/7.5.4
           This does not get rid of it (notes-history on home view) but does force the provider to only allow records the logged in user has “rights” to.

```
B – Edit the source code in argos-saleslogix: Application.js:getDefaultViews function – it returns an “array list”.

C – Create an override to getDefaultViews in a custom module add-on:
             Lang.extend(Mobile.SalesLogix.Application, {
                          getDefaultViews: function() {
                                    var views = [
                                       ‘account_list’,
                                         …..
                                   ];
                                  Return views;
                         }
            ) };
```

I’ve done all of them but am standardizing on option “A” (for 7.5.4 slx w/1.2.and  2.x on 754) since it is the OOTB approach in SLX Vers 8.0.

## rjl

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by sturev-zz** [comment]
Thanks RJ...  I caught the function in the Application.js but I'm not seeing how to remove it from the Configure page.  The user can go in and enable notes/history and it shows back up on the home screen.  Have you dealt with that before?

**Comment by jbest84** [comment]
The 7.5.4 for 2.0 module has an example of this here: https://github.com/SageSalesLogix/argos-saleslogix-20_for_754/blob/2.1/src/ApplicationModule.js#L82 and https://github.com/SageSalesLogix/argos-saleslogix-20_for_754/blob/2.1/src/ApplicationModule.js#L97

**Comment by sturev-zz** [comment]
Thanks Jason...  I was trying not to wire up an override but I forgot I had the backcompat so I just threw it in there.
