### ISSUE TITLE
3.3.1 Custom list quick actions added multiple times

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-saleslogix#391]
On 3.3.1 mobile I have an Application Module that registers quick actions for the opportunity list. The code registers 3 new actions (See code http://screencast.com/t/V73gNhXt9F). The problem is that the custom actions are added when the app loads, but then also added again each time you expose the quick actions. See video here: http://screencast.com/t/6CZ0QvMse7 You'll notice the first time I expose the quick actions the 3 custom actions (Won, Lost, & No Dealer) are shown twice each (loaded once when the app loaded and again when I exposed the quick actions). Then each time I expose the quick actions they are duplicated yet again (so if I expose the quick actions 20 times, they will each be repeated 21 times)

**Comment by RyanFarley** [comment]
Just to mention, the actions are also duplicated in the "configure quick actions" menu as well http://screencast.com/t/y7dWu4JwSk

**Comment by jbest84** [comment]
Thanks for the report. I will check it out.

**Comment by jbest84** [comment]
Fixed in the SDK here: https://github.com/Saleslogix/argos-sdk/commit/d1b28d3e617f2b4cb4549f47eb2bce1ebb4dc6fc

**Comment by RyanFarley** [comment]
Awesome. Thanks Jason.

**Comment by jbest84** [comment]
@RyanFarley Sorry - There was one additional commit on top of this:
https://github.com/Saleslogix/argos-sdk/commit/35109a30057369f7484173f7df70802adcc7827e#diff-15a1a96effa8f9210d4d73babad92b03

The configure list still had the dups.

**Comment by RyanFarley** [comment]
Got it. Thanks again.
