### ISSUE TITLE
v3.2.1 - default caching causing issues

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#393]
We have a module that uses Google maps and make a reference to the maps api:

>   
>      ... text/javascript  src= "https://maps.googleapis.com/maps/api/js"></script> 

When we use index.aspx (or html) has:

>   
>    ... manifest="index.manifest.ashx">
>   

just before the header

Google has made changes in their api such that the map will not display if the above ref to the manifest  is in place. By removing it (basically changing it into index-nocache.aspx/html) then all is ok on the mobile device

Is there some way to change how this works such that it does not "touch:" the ref to the Google api without resorting to the (complete) nocache approach?

**Comment by jbest84** [comment]
Can you try adding the maps.googleapis.com domain to the NETWORK section in the template.manifest file?

https://github.com/Saleslogix/argos-saleslogix/blob/develop/template.manifest#L40

**Comment by rjledger** [comment]
Would I just put in:
  https://maps.googleapis.com
?

## 

RJLedger – www.QuantumLeapSolutions.nethttp://www.QuantumLeapSolutions.net
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by rjledger** [comment]
put in https://maps.googleapis.com

no joy.

**Comment by jbest84** [comment]
Just try *

**Comment by rjledger** [comment]
This may have done the job! Now I have to figure out what changed in the Google API in resize.. “touch” is not working on the map ☹

## 

RJLedger – www.QuantumLeapSolutions.nethttp://www.QuantumLeapSolutions.net
Blog: www.rjlsystems.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by rjledger** [comment]
Thanks!

**Comment by jbest84** [comment]
No worries. If you get a chance check our 3.4-beta1, or feel free to pull from develop. We are trying to gather some feedback.
