### ISSUE TITLE
How to use the BUILD too create a zip file?

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#394]
Are there any hints/docs on using the build to make our own VFS bundle?

**Comment by jbest84** [comment]
You can run `grunt bundle`. The output will be in the deploy folder.

EDIT: [Here](https://github.com/Saleslogix/argos-saleslogix/blob/develop/build/bundle.bat) is the script the grunt bundle command uses. If you call it manually you would need to pass in a version number: `build\bundle.bat 3.4`. The bunder.exe that is used is located in the argos-sdk under tools.
