### ISSUE TITLE
Reference to non-existing Contracts View in all versions

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#395]
In ApplicationModule.js the "define" calls out:
    './Views/Contract/List' 
and in the function side:
    ContractList 

Plus gets called out to register a view:
            this.registerView(new ContractList({
                id: 'contract_related',
                expose: false,
                defaultSearchTerm: function() {
                    return '';
                }
            }));

I have a custom module for "Contract" for one of my customers and this is causing it to fail when I register since it's already registered a non-existing view.

**Comment by jbest84** [comment]
The view [does](https://github.com/Saleslogix/argos-saleslogix/blob/develop/src/Views/Contract/List.js) exist though, it is used in ticket edit:

```
{
      label: this.contractText,
      name: 'Contract',
      property: 'Contract',
      textProperty: 'ReferenceNumber',
      type: 'lookup',
      requireSelection: true,
      view: 'contract_related',
      where: this.formatAccountQuery.bindDelegate(this),
}
```

Are you giving it a  unique id when registering it (if you are creating different instances of it)?

**Comment by rjledger** [comment]
Ok.. found it. I need to replace it completly. Isn't there a way to de-register it?

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jbest84** [comment]
You can destroy the views if you want, there was an example of that in the 754 compat module: https://github.com/Saleslogix/argos-saleslogix-754/blob/2.2/src/ApplicationModule.js#L61

**Comment by rjledger** [comment]
Thanks! I should have looked. At a clinic all week and will do it as soon as I get back.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by rjledger** [comment]
Tried it – no joy – caused a lot of issues and really did not get rid of it. Also, there’s a “related view” under Accounts and it will not “go away”.

I see only one reasonable course – directly “hack” the Infor code and cut out all references to “contract”. If I do that I know my custom module will work.

## 

RJLedger – www.QuantumLeapSolutions.nethttp://www.QuantumLeapSolutions.net
Blog: www.QuantumLeapSolutions.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
Destroying the view won't remove it from the layout of other views. You would still need to remove those layout [items](https://github.com/Saleslogix/argos-saleslogix/blob/develop/src/Views/Account/Detail.js#L213). [Here](https://github.com/Saleslogix/argos-sample/blob/master/src/ApplicationModule.js#L291) is an example of removing an item from a detail layout.

**Comment by rjledger** [comment]
Thanks! My “brain” is suffering from lack of snow… it’s been raining and we should have had at least a foot or two. ;-)

## 

RJLedger – www.QuantumLeapSolutions.nethttp://www.QuantumLeapSolutions.net
Blog: www.QuantumLeapSolutions.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987
