### ISSUE TITLE
v3.4 Gold downloaded today from Download center - error on loading app

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#397]
Firefox sees an error loading the "app":
L20n: No resources found. (Put them above l20n.js.)
http://slxpc2013:3333/informobile/content/javascript/argos-dependencies.js
Line 4

**Comment by jbest84** [comment]
That is an expected message, with how we are using L20n. Basically it is expecting l20n script sources to appear before it. We load them via code later on in the page lifecycle.

**Comment by rjledger** [comment]
So otherwise we should not see any additional side effects of this - right?

rjl

## 

RJLedger - www.QuantumLeapSolutions.nethttp://www.QuantumLeapSolutions.net
Blog: www.QuantumLeapSolutions.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
Correct.

**Comment by jbest84** [comment]
Also, there is a known issue with the date/time picker in activities. You have to input meetings that start/end on the hour manually, the selector will not let the user select 00 or 05. We will have a fix in 3.4.1 shortly.
