### ISSUE TITLE
v3.4 Gold downloaded today from Download center - Configure

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#398]
If I log in, go to configure and pick ALL items, save - all is ok

Do a clear storage, log out, in - go to configure, the last item is not "selected", all teh rest are.

**Comment by jbest84** [comment]
This is expected. "My Activities" is no longer a default view. We kept it in the product if people want to opt in to use it. "My Schedule" is now the default, and is limited to the current day. This new view also has the new "briefcase" functionality, which will allow you to download the day's activities + all related data for offline. We might expand the dataset to a week, if a day is not enough for most people.

**Comment by rjledger** [comment]
OK.
  I'd prefer a week view - is there an easy way to customize this?

rjl

## 

RJLedger - www.QuantumLeapSolutions.nethttp://www.QuantumLeapSolutions.net
Blog: www.QuantumLeapSolutions.net/blog.html
Office: +1 603.369.3047 x101
Direct (DID): +1 603.369.4987

**Comment by jbest84** [comment]
Yes you can customize the UserActivity model. I updated the sample on how to customize the new model system here: https://github.com/Saleslogix/argos-sample/blob/master/src/ApplicationModule.js#L413-L427
