### ISSUE TITLE
Views SalesOrder Entity - List.js "error"

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#4]
contentTemple:
   Now:              '<h4>{%= SalesOrderNumber %}</h4>'
   Should be:    '<h4>{%= $.SalesOrderNumber %}</h4>'

**Comment by jhershauer** [comment]
Thanks RJ. SalesOrders are not currently part of the mobile client, so we weren't doing any work/validation of these views that had been started by a contractor back before v1.0 came out.

We'll either delete these extra views or do a sweep of them before we add them back into the project.

Thanks,
Jeff

**Comment by rjledger** [comment]
You're welcome Jeff.
I'd suggest you leave them in as is. Some of us have been expanding on SO's, Defects, Returns, Campaigns, etc for some of our clients and it would be a big (dev/support/time consuming)mess for us to have to re-incorporate them back in.

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
