### ISSUE TITLE
Date time display on related activity list view

### ISSUE THREAD

**Issue by greensweater** [Saleslogix/argos-saleslogix#40]
This issue may only be present on the 1.2 branch but the code is the same in the current master. In the contentTemplate simplate the following line:
`'{%= $$.activityTimeTemplate.apply($) %}',`
...doesn't work. Format.date format string argument gets a null, so output is in the default m/d/yyyy format.

For comparison, the below is from the contentTemplate simplate in calendar/UserActivityList:
`'{%! $$.timeTemplate %}',`

I used the following code:
`'{%! $$.activityTimeTemplate %}',`
After switching out the above code in the activity list view, the list is displayed correctly in 1.2.

**Comment by wskidmore** [comment]
Thank you for catching that! I've updated both the master branch and the 1.2 branch so that the template is called with the correct scope.

**Comment by greensweater** [comment]
Thanks.
