### ISSUE TITLE
V3.4 - Gold -Briefcase

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#400]
Is there a good place to look to see how to add briefcase capability to a custom entity? 

I see:  enableOffline: true,
but doing this only gets me part way there - I get an alert  and teh error log is complaining about "model not found".
SO we have to re-write the custom to make this work?

**Comment by rjledger** [comment]
.. what I have been discovering - for us to give our customers "briefcase" functionality" to any existing mobile customs - it will be a significant re-write of the customization - This is not a practical/profitable thing to do.. Not sure I want to attempt it :-(

**Comment by jbest84** [comment]
It is not that significant. See [this](https://github.com/Saleslogix/argos-sample/commit/edc02e7e0cc49ed7fdc49f93e75bbe49e9c8e9c9) commit on argo-sample.

**Comment by rjledger** [comment]
Doesn't solve the problem for lack of documentation for custom entities on how the whole "model" thing is setup.

AFAIK there's no documentation on how all of this was done from scratch too finish. - Do not agree this issues shoudl be closed at this time - missing a lot of documentation here.

**Comment by jbest84** [comment]
Nearly every entity was converted to have a model. You can use those as a working example for custom entities. Here are two powerpoint presentations from Tech Tuesday that explain the model system in 3.4, and the src/src-out changes:

[Mobile src-out changes.pptx](https://github.com/Saleslogix/argos-saleslogix/files/493642/Mobile.src-out.changes.pptx)

[Infor Tech Tuesday Mobile Offline.pptx](https://github.com/Saleslogix/argos-saleslogix/files/493641/Infor.Tech.Tuesday.Mobile.Offline.pptx)
