### ISSUE TITLE
Problems with Firefox in Mobile and Tablet

### ISSUE THREAD

**Issue by Iveth** [Saleslogix/argos-saleslogix#401]
Hi, I have a problem with my CRM, I work with argos-saleslogix-20_for_754, but this version doesn't work in Firefox Version 46.0 in Tablet or Mobile, the last update of Firefox made that the aplicattion doesn't work it.

I need help for resolved this issue.

Regards.

**Comment by jbest84** [comment]
This module is not actively supported/developed. Mobile 3.0 was the last supported version.
