### ISSUE TITLE
4.0 suggestion - get rid of detail-header

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-saleslogix#403]
In the current build of v4.0, there is a div with class=detail-header. This node shows "Information on {Entity}" with significant padding and an 18px font. IMO this is an unnecessary use of space and it doesn't really add any value. I think dropping the detail-header altogether is a better route.

With detail-header:
https://cl.ly/0h110d2I3b0l

Without detail-header: 
https://cl.ly/0n373d391w0r

Ryan

**Comment by jbest84** [comment]
Copied to our internal (JIRA) tracker.

INFORCRM-19114
