### ISSUE TITLE
Overiding the Items in the List View now that we have groups - How To?

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#404]
Subject says it - I know there must be a way but have not found it. It appears there is something in ACCOUNT that eludes to this but I don't see anything like it anywhere else nor is there an example on this. Customer wants to see the Address.Description under the ACCOUNT but wants the label to say something like "Location". I can see that if I mod the ItemTemplate and do a lookup it shows correctly - however, if I then "clear" and get back to the "Group" (say All Accounts) none of that is there. IMHO it looks like I have to override groupLayoutItemTemplate but all attempts so far have resulted in zip..nada.. nothing.. no errors.. no change!

PLEASE point me in the right direction - do I have to also mod query (model sdata) and something else?? If I added something to groupLayoutItemTemplate would I use Address.Description.. and what about the label being different? can I hard code it?.. looks like I cannot.

Tried in 3.4/3.5/3.6 - same results in all cases :-(

**Comment by jbest84** [comment]
The best bet would be to create a group where these fields are first in the group layout. The group layout is dynamic and will take the first N fields in the group layout. If you want to use sdata entities for the list, you can adjust the template like you normally would and set the groupsEnabled flag on that list to false ([example](https://github.com/Saleslogix/argos-saleslogix/blob/3.6.x/src/Views/Account/List.js#L55)).

All the dynamic code for groups is in the [_GroupListMixin](https://github.com/Saleslogix/argos-saleslogix/blob/3.6.x/src/Views/_GroupListMixin.js#L288).

**Comment by rjledger** [comment]
I passed the info on to the customer - not really happy with the solution and sees it as a work-around. Believe the actual BP involved has or will be submitting an official "bug" issue on this one thru normal channels.
