### ISSUE TITLE
Insert Activity 404 error

### ISSUE THREAD

**Issue by nrice** [Saleslogix/argos-saleslogix#41]
Trying to insert activity:

http://localhost:3377/sdata/slx/system/-/activities?_includeContent=false&select=AccountId%2CAccountName%2CAlarm%2CAlarmTime%2CCategory%2CContactId
%2CContactName%2CDescription%2CDuration%2CLeader%2F%24key%2CLeadId%2CLeadName%2CLocation%
2CLongNotes%2COpportunityId%2COpportunityName%2CPriority%2CRegarding%2CRollover%2CStartDate%2CE
ndDate%2CTicketId%2CTicketNumber%2CTimeless%2CType%2CUserId%2CRecurring%2CRecurrenceState%2C
RecurPeriod%2CRecurPeriodSpec%2CRecurIterations&format=json&_t=1338850990404

I get error:

[
  {
    "severity": "Error",
    "sdataCode": "ApplicationNotFound",
    "applicationCode": "",
    "message": "Unable to locate a handler to process the request 'slx/system/-/activities'",
    "stackTrace": "",
    "payloadPath": ""
  }
]

Looking at my Activity entity I do not have a RecurringState property.

Also RecurPeriod, RecurPeriodSpec, and RecurIterations do not match the case of my properties.  Do I need to do something  additional to get this to work?

Thanks!

**Comment by mmorton** [comment]
The recurring activity support requires a semi-recent build of the upcoming 8.0 release.  Are you trying this (from the `master` branch sources) against 8.0?

**Comment by rjledger** [comment]
Was not the original plan to make the Mobile 2.0 (dojo based) to be able to detect what version SLX and "fall-back"? This was discussed at BootCamp last November... and it had been that way for some time.

Also Issue #32 specifically discusses the "fall-back" situation and needs to be addressed.

**Comment by nrice** [comment]
Even though it says 1.2  Is this not 1.2?  What should I be using for a stable release for a client?  Thanks!

**Comment by rjledger** [comment]
Norm,
 The "master" is not 1.2... it's really the dojo based 2.0 - however, it is supposed to "fall-back" and run w/a 7.5.4 system. I have an earlier snapshot of the dojo 2.0 on our production (been running 2.0 since last fall ;-). We show the 1.2 to customers and then the 2.0.. they like the 2.0 better.. and we deploy it to their systems.. I'm not keen about the 1.x series... and use it (very) reluctantly when I have to.
