### ISSUE TITLE
V1.2 (and probably 2.0 - have not checked yet) bug

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#42]
When completing an activity the HISTORY.RESULT is set correctly but the HISTORY.RESULTCODE is not set.

Windows/LAN (and web I believe) do set it.

**Comment by rjledger** [comment]
It's definitely (still) broken in 2.0 as well as the 2.1 release. Just tested it on a "complete" and there was no "CON" ResultCode value.. and there should be.

**Comment by jbest84** [comment]
Fixed by https://github.com/Saleslogix/argos-saleslogix/commit/608f3628080968c46a35d95ba1cdd7a75c081427
