### ISSUE TITLE
Calendar controls unresponsive on iOS 13 in mobile 4.0

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-saleslogix#447]
In mobile 4.0 on iOS 13.1.2 the calendar controls are not responsive. Clicking a day highlights it in grey, but today stays highlighted in blue, also arrows to step by month does not function, nor the day/week toggle.  Month/Year dropdowns seem to be the only parts that work.

There appear to be two defects logged for this on Xtreme - see https://share.getcloudapp.com/jkunGL6O

Are these on the radar for fixes anytime soon? I didn't see any commits that look related so far. Thanks!

**Comment by jbest84** [comment]
The fix was done in the SDK for this, and should go out with 4.1:
https://github.com/Saleslogix/argos-sdk/commit/df5d34dad74907a40cb8fbc2241a4a0f48515d6f

Attachment fix for IOS 13 as well:
https://github.com/Saleslogix/argos-sdk/commit/20a58b93a228f4931989d49ea596326f8c95fa90

**Comment by RyanFarley** [comment]
Thanks Jason

**Comment by RyanFarley** [comment]
Jason, any timeline for when 4.1 comes out? Just trying to decide if I should merge in the fixes for my customer or wait for 4.1. Thanks.

Also FYI, the wiki page for 4.0 changes on argos-saleslogix and argos-sdk still state that 4.0 is not yet released.

**Comment by jbest84** [comment]
I believe the original target was for March/April, but that could change. Updated the wiki pages, thanks!
