### ISSUE TITLE
v1.x and v2.0+ - Missing the ability to assign Account Manager and Owner

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#45]
Do not know how I missed this one:

If you go to Account(s) and add an Account you can select the Account manager and the "Owner".

However, if you use the "Quick Action" to Add Account/Contact you cannot - 

Notice - not ALL "codes" are legit for an Owner - it has to be an "Active" user(ID), or Team - never a template or "retired" user

**Comment by rjledger** [comment]
2.1 is "broken as well - Just verified it.

**Comment by rjledger** [comment]
2.2 is "broken" as well - just verified it

**Comment by jbest84** [comment]
@rjledger QA has filed a defect in our system for this. It will get worked into 2.3.

**Comment by jbest84** [comment]
Fixed in commit: https://github.com/Saleslogix/argos-saleslogix/commit/2ed6be9787bfac7fd8672f0d4a72ef455f2fa365

**Comment by jbest84** [comment]
@rjledger The other issue you filed deals with active/template users. I see you mentioned it in here as well. It was fixed in commit: https://github.com/Saleslogix/argos-saleslogix/commit/b84f26c107160b300e4d38741b8e2e17bc351c7a

**Comment by rjledger** [comment]
I'll "hack" this (commit: b84f26c) into my 2.x (currently 2.2) and test it out this weekend - after the 4th celebration of course ;-)

**Comment by rjledger** [comment]
Ran a test and ran into on issue so far:
    The fix to "Owner" is not filtering out Departments - Departments cannot be "owners".

**Comment by jbest84** [comment]
@rjledger The web client currently allows Departments for 8.0. Are departments a problem with sync too? I had QA look and we were not able to find any open defects around this for 8.0.

**Comment by rjledger** [comment]
OK.. so I’d say it’s broken defective in the web also. If you look at the Windows/LAN client you will see it has never allowed departments (14+ years of never ;-)

Users (both the “default” as well as the USERID – “pr” (pr-records), teams, and “everyone” (SYST00000001) are the only OOTB legal owners/SECCODEID values.

Also, check the Saleslogix documentation & with the training folks – same thing.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jperona** [comment]
@rjledger we'll get it looked at to make sure we get a consistent story

**Comment by jbest84** [comment]
@rjledger In the meantime, you can cherry pick this commit if you want: https://github.com/Saleslogix/argos-saleslogix/commit/122673454e8eed62f4ab08e7d8fb0247ab342815

**Comment by rjledger** [comment]
John,
Sounds like a plan!

.. IMHO – it should work like the Windows/LAN world.. however, if you do change it, Windows/LAN should be changed as well since there’s a LOT of customers out there that run “hybrid/mixed” client environments. If anyone is different it causes conflicts/issues in the other.
rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by rjledger** [comment]
@jason – will do!

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by rjledger** [comment]
Worked just fine!
Time to have a beer.. and quit for the weekend ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
Cheers! 
![beer](http://blog.mlive.com/kalamabrew/2008/03/small_Beer%20Mug%20Icon.jpg)
