### ISSUE TITLE
2.0 Mobility - unable to enter phone number using alpha characters

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#49]
Windows/LAN and web allow you to enter using alpha characters and then "translates" it into a number:
    ex: 800GOVALLEY  or 800FOXBORO
Mobility just "falls over" and tosses the characters so you end up with just "800" and nothing else.

**Comment by jbest84** [comment]
This is actually a bug in argos-sdk (v2 and master): https://github.com/Sage/argos-sdk/blob/master/src/Fields/PhoneField.js#L116

Can you please move this defect to that repository instead?

**Comment by rjledger** [comment]
Moved to argos-sdk
