### ISSUE TITLE
2.0 Mobility - unable to enter(or edit) extension in any phone number field/control

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#50]
If you are using FF/chrome, etc on the "desktop" you can enter/display/edit an extension on a phone number just like you always have been able to do so in Windows/LAN an web.

If you use certain mobility devices (ex: my driod X or my Samsung Galaxy tab) it pops up a different keyboard that has no provisions for addding/edting an extension (no "x").. and it will "kill off"/delete an extension of there is one there! In other words, it will delete customer data.

**Comment by jbest84** [comment]
Please move/copy this defect over to argos-sdk: https://github.com/Sage/argos-sdk/issues?state=open

**Comment by rjledger** [comment]
Moved to argos-sdk
