### ISSUE TITLE
Users not getting "update available" message after new deployments in 4.2.0

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-saleslogix#502]
I have a mobile customer using 4.2.0 that does not get the update available notification in mobile after a new deployment. In the console I see a lot of cancelled service worker requests, which appear to be attempts to pull the new/updated files. See https://share.customerfx.com/eDu57vyG

Is this an expected side effect from the changes in issue #455 with Chrome deprecating application cache or should application updates still work the same way?

Users are unclear how to get new changes after they are deployed. With those requests failing, it seems as though some users can see the changes immediately by refreshing their browser and others don't until their browser cache has been invalidated - possibly a difference between iOS and Android browsers deal with cache since iOS users seem to see things right away, android users don't until some time has passed - either way, not sure how this is supposed to work now or if it's different than before?

Thanks,
Ryan

**Comment by jbest84** [comment]
@RyanFarley - Service worker requires HTTPS. In version 4.3 we will show these errors to the user if the service worker is failing to register. Also, the service worker uses a cache version on line 1:

https://github.com/Saleslogix/argos-saleslogix/blob/develop/serviceworker.js

If they are bumping the version of their customization they should probably update that cache version or have a run once that deletes the cache. 

The files that the service worker will attempt to cache are provided in the index-body.acsx control:

Markup: https://github.com/Saleslogix/argos-saleslogix/blob/develop/index-body.ascx#L20
C# Codebehind: https://github.com/Saleslogix/argos-saleslogix/blob/develop/index-body.ascx.cs#L95-L112

When the page loads, you should be able to see this in Chrome's devtools if you look at the page source, and search for cacheFiles.

**Comment by RyanFarley** [comment]
This implementation is using HTTPS, still seeing the errors.
Also, not changing the version of their customization module each time, should they be?

**Comment by jbest84** [comment]
Can you open Chrome devtools on that site and break on exceptions in the Sources tab, or set a breakpoint at line 87 and see what is going on? Prior to doing this, you can clear all caches by going to the Application tab -> storage -> Clear site data.

![mobile-serviceworker](https://user-images.githubusercontent.com/354553/165806488-dadc9f02-4ba7-4997-946b-8ea8c793a256.PNG)

Are there any adblockers running that might be blocking the requests? I know sometimes uBlock Origin blocks these for me.

**Comment by jbest84** [comment]
The "addall" command is being sent from the argos-saleslogix application:

https://github.com/Saleslogix/argos-saleslogix/blob/4.2.x/src/Application.js#L208

**Comment by RyanFarley** [comment]
Jason, it turns out that it was an ad-blocker that was stopping the requests. I've let the client know. 

Just for FYI, the ad-blocker was AdGuard.

**Comment by jbest84** [comment]
@RyanFarley  - Thank you for the update. uBlock Origin does similar things with the offline ping request as well.
