### ISSUE TITLE
ERP fields from BOE module unavailable to customize in ApplicationModule

### ISSUE THREAD

**Issue by RyanFarley** [Saleslogix/argos-saleslogix#515]
I need to modify some of the fields added in the BOE modules. The issue is that since these are dynamically loaded based on BOE enabled in the system integrations, they aren't added by the time my ApplicationModule loads customizations. 

How can I modify/remove the ERP fields using registerCustomization in my AccountModule?

Thanks,
Ryan

**Comment by jbest84** [comment]
This came up a while back in the argos-sample repo. Here is a link to a code snippet to work around this limitation:

Modifying a BOE quick action:
https://github.com/Saleslogix/argos-sample/issues/9#issuecomment-1601872525

Here was another modifying one of the BOE picklists:
https://github.com/Saleslogix/argos-sample/issues/10#issuecomment-1677288059

**Comment by jbest84** [comment]
Also - In the future it would be nice to expose an API so the customization hooks have access to the original layout, and the modified layout.

**Comment by RyanFarley** [comment]
Thanks Jason. That was just what I needed. Yeah, an API would be great, but this route wasn't too bad.

**Comment by jbest84** [comment]
Glad it worked out for you!
