### ISSUE TITLE
Not really an issue but a suggestion

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#6]
Add a "favicon" to the SData html5 Mobile app.

It turns out there's already an image of the "Blue Ball" in content/images (icon.png).

What I did was to just add one line to the "index" under the <title...</title> (tag) line:
           <link rel="shortcut icon" href="content/images/icon.png"  />

Now you get the "Blue Ball" up on top of your browser ;-)

Also wrote a small blog on it:
http://blog.rjlsystems.net/2011/07/28/add-a-favicon-to-your-sage-saleslogix-mobile-web-client/

**Comment by jbest84** [comment]
Fixed via https://github.com/Saleslogix/argos-saleslogix/commit/d7765dff78875082814a29f1f3d84805b271588c
