### ISSUE TITLE
(new) tickets not showing up..

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#8]
Scenario:
A  -  Looked up an Account and then related tickets. 6 tickets (correctly) showed up.
B - Via Windows/LAN, crested 3 new/additional tickets for that account
C - Went back to the mobile (still showing the original 6)  and click on the "back" button/arrow next to "home".
D - Clicked on the related tickets and still only showing 6 tickets.

No matter where I navigated or how I navigated, still only the original 6 would show up. Only by logging out and then back did it then properly show all 9.

**Comment by jhershauer** [comment]
That's FAD. The view is cached. The view will be refreshed if:
1. You make any updates in the mobile client.
2. You hit the browser refresh button (or hot key)
3. You log out/in.

I'd use the browser refresh, with the client in "remember me" mode.

Thanks,
Jeff

**Comment by rjledger** [comment]
OK...
Not sure that the preset FAD is good... I was testing a typical scenario:
    A - User is in the field on his/her "mobile/tab" device
    B - "Someone" adds a ticket, updates info, etc... at the home office (or somewhere else using one of the client apps - even remotes synching data in).
    C - the user (A above) has no idea there are new tickets, etc because there is no "notification" mechanism.

This is a bit of a hole in the user experience.

I'd suggest that when one "moves" to a new "view" in the mobile app it immediately looks to see if there is new data and grabs it from the server (and does the normal html5 cache operations).

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----

**Comment by jhershauer** [comment]
Ok, thanks for the feedback. I'll create a story item for this to discuss with the team. If the user really finds it awkward to hit refresh to see new data, then we can look into alternatives. 

We're trying to find the right balance between speed and usability. For customers who aren't dealing with lots of real-time udpates, the abillity to move quickly around the app without data refreshes taking place on every click is probably an advantage.
