### ISSUE TITLE
2.1 mobility - GH Source - Build issue?

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#81]
Just copied the source(s) for 2.1 over to my test 754 env (along w/the updated 20 for 754).

"Manually built the pieces (sdk, saleslogix, etc...)" and "manually" deployed them (no different than I did w/2.0).. and tried to "run".. and hit an error (FireFox):
      NetworkError:  404 Not Found - http://localhost:3333/slxmobile21/content/dojo/dojo/store/util/QueryResults.js

FYI - runs off the "source" just fine.. just seems to have a build issue.

**Comment by jbest84** [comment]
@rjledger That file is in the build script: https://github.com/SageSalesLogix/argos-saleslogix/blob/2.1/build/release.jsb2#L591 and in the file system: https://github.com/SageSalesLogix/argos-sdk/tree/2.1/libraries/dojo/dojo/store/util

Added in this commit: https://github.com/SageSalesLogix/argos-saleslogix/commit/c36a781897eb42a4f50cff6d1a8f0025bc666c13

**Comment by rjledger** [comment]
I don't consider this closed.......
The file(s) and build script (you linked to) are the ones I used.. but it's still not building a large piece of the dojo part(s)... something is not right here.
From what I see, it looks like it's a build issue w/argos-sdk. I'm using the latest "gist" to do the build.. but still do not get all the pieces under "dojo" in the deploy folder - any ideas?
