### ISSUE TITLE
Still problems w/2.1 build... ref my prev bug submittal

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#82]
First.. please do not close this until I've verified that I can build properly..

The file(s) and build script (you linked to) are the ones I used.. but it's still not building a large piece of the dojo part(s)... something is not right here.

From what I see, it looks like it's a build issue w/argos-sdk itself.

I'm using the latest "gist" to do the build.. but still do not get all the pieces under "dojo" in the deploy folder - any ideas?

**Comment by jbest84** [comment]
The build script that includes this file is in argos-saleslogix, not the sdk. We use the same build scripts to automate our QA sites.
- Verify the contents of \deploy\content\dojo\dojo-dependencies.js (Search for QueryResults)
- Ensure your cache is cleared (HTML5 application cache included)
- Try hitting your mobile site using index-nocache.aspx

**Comment by rjledger** [comment]
Did all of that previously.. still no joy.

In fact, I went back to my 2.0 and tested it as well to see if I had done something wrong.. it built and I was able to copy/run (the 2.0) just fine.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by rjledger** [comment]
OK.. I’ve gone back and did a total wipe (‘nuke) of my dev environment. Re-deployed everything… did a build-module saleslogix… copied the “deploy” folder contents to the “root”.. and fired up FF (20.0.1) (yet) again… and now we are working!

“Something” had to be messed up in my dev image update from 2.0 to 2.1 .. who knows what. All I can say is throw the “old” away and go clean…
Appreciate the responses big time.. and let’s close this issue – OK?

Thanks again - rjl

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
Great!
