### ISSUE TITLE
No easy way to change the order of List Actions, etc (List anything)

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#85]
It is a very common customization to add/remove and/or change the order of List Actions. registerCustomization handles insert/remove (add/delete) just fine - however there is no way to change the order unless you either:
    a - modify the OOTB code directly
    b - use registerCustomization and do remove/insert

The first way is not desirable for upgrade reasons/maintenance. The second method is rather laborious and very messy.

Also.. changing the order of "List Anything" - related entities under any entity  - suffers the same way (as List Actions).

**Comment by rjledger** [comment]
Anyone have any thoughts about this issue? I'm still having to do extensive "hacks" to the OOTB code itself in order to avoid wasting a ton of time trying to do "delete and insert" in a custom module.. and even then cannot do all of what is needed by our customers.

**Comment by jbest84** [comment]
List actions in 4.0 are configurable and sortable.
