### ISSUE TITLE
Scheduling an Activity (or follow-up) - Duration too restrictive

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#9]
Duration only allows choosing a predefined set of times:
       none
       15 minutes
       30 minutes
       1 hour
       1.5 hours
       2 hours

We need to be able to set a start date/time and end data time and let the system figure the duration...
AND
to be able to set a start date/time plus enter a free format duration. (ex 23m - 23 minutes, 5.5h)

As it is now, it's very close to unusable.

NOTE: Needs to have a "GUI" capability like the Windows/LAN client. Also, noticed we have "hard-wired" defaults on alarms at 15 min. Not that way in other Slx Client apps (Web/Win)

x-posted to Community

**Comment by rjledger** [comment]
Had a customer comment to me the LAN/Web approach is far better/easier/more flexiable to use than the current GUI in the mobile.

**Comment by wskidmore** [comment]
There is now a field `type: 'duration'` which is similar to the Web. It allows a user to type in any value with auto complete and a picklist option for the defaults. Auto complete handles short-formats, i.e. `h`, `ho`, `hou`, `hour`, all end up as `hours`.

https://github.com/Sage/argos-sdk/blob/master/src/Fields/DurationField.js

Note that it only accepts a single unit, so 1h 30m would have to be expressed as 1.5h, or 90m.

**Comment by rjledger** [comment]
Tested it.. looks great!

## 

RJLedger – www.rjlsystems.net
Blog: blog.rjlsystems.net
Phone: +1  508.809.9513

-----Original Message-----
