### ISSUE TITLE
2.2 - Attachments - Unable to open

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#95]
Not sure if this is still a "WIP" (Work In Progress" - but - I loaded the latest argos-sdk/saleslogix into my 8.0 test site and ran into issues w/attachments.

Specifically:
  1 - on the desktop using latest FF - clicking on an attachment hyperlink brought up the Slx (SData) dialog request for username/password. Tested w/two SLX users - admin and "lee".

  2 - on my Andrioid Samsung Galaxy tablet - nothing happens if I click on an attachment hyperlink.

**Comment by rjledger** [comment]
.. to add... just tried it on my DroidX - same results - nothing happens.

**Comment by jbest84** [comment]
@rjledger We are aware of the issue. We are planning on another sprint before 2.2 is released.

**Comment by rjledger** [comment]
Glad to know…
When you have something I’d be more than willing to run it up on my systems.

I’m also building my own version(s) of the “20 on 754” stuff so that I can run more of these advanced enhancements in 754 environments. Right now I can run all the new features (except the role based security) of 2.0/2.1 on 754. We’ve deployed a lot of this to customers and use the GH sources exclusively.. not the SalesLogix downloads.

## rjl

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)
