### ISSUE TITLE
2.2 - Not a great user experience on a smartphone - productivity loss

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#97]
A - Great on the desktop w/a browser
B - Great on a tablet (ex: galaxy 10.0).. will test on a 7 inch
C - Not great.. (in fact it reduced productivity) on a smartphone..

My smartphone is a DroidX and has a very big screen.. in portrait mode - useless - in landscape mode - partially useful.

2.2 needs to (dynamically) understand what it is running on and adapt. It needs to fall-back (automatically) to a typical "2.1" view mode for smartphones.

Can't see deploying this to any of my customers if it goes out the door like this.

**Comment by jbest84** [comment]
@rjledger Can you give more examples on point C? Why is this a productivity loss on a smartphone?

**Comment by rjledger** [comment]
Screen area issue pure and simple. I’ve shown it to a couple of other folks and they agree w/me.

It’s way too crowded.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jbest84** [comment]
Is this due to the new menu or the fixed toolbar at the top?

**Comment by jperona** [comment]
@rjledger Thanks for the feedback, but it would be good to better understand what specifically is the issue on a phone.

**Comment by jbest84** [comment]
@rjledger 
How exactly does the screen feel too crowded? Is it the fixed toolbar at the top now? Is it the menu? The global menu saves a lot of “back” navigating to get back to the old home screen. Just a note, this menu is part of the SDK now and is customizable. So if you wanted the old behavior you could override “navigateToHomeView” in Application.js and change it to load the old homeview, and NOT call the loadSnapper function. Could you provide screenshots via http://imgur.com possibly?

**Comment by rjledger** [comment]
Hi John,
  It’s the screen size. It’s way too crowded and busy on a phone. I could not even use it in portrait mode and hard to use/navigate in landscape.

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by rjledger** [comment]
Now that we have the "final".. looks like it's pretty good. Still running some tests on different devices. One customer expressed some concerns using in on smartphones (droids).
