### ISSUE TITLE
2.2 - still has Sage all over it

### ISSUE THREAD

**Issue by rjledger** [Saleslogix/argos-saleslogix#98]
ex: 
   Copyright on login screen has Sage - Shouldn't this now be Swiftpage or SalesLogix?
   Title at top says "Sage SalesLogix"
..

**Comment by jperona** [comment]
@rjledger Branding is on our list of items, 2.2 is not complete so I hope we'll have that information soon.

**Comment by rjledger** [comment]
Was just wondering if (hoping)  2.2 would get the new brand ;-)

## 

RJLedger – www.rjlsystems.nethttp://www.rjlsystems.net/
Blog: www.rjlsystems.net/blog.html
Direct Phone: +1 603.369.3047  (alt: +1  508.809.9513)

**Comment by jperona** [comment]
I think we can close this as we've removed sage

**Comment by rjledger** [comment]
Definitely!
